# Generated by Django 4.2.21 on 2025-08-22 14:59

import django.db.models.deletion
import select2.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Name")),
                ("description", models.CharField(max_length=200, verbose_name="Beschreibung")),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Reporttyp",
                "verbose_name_plural": "Reporttypen",
            },
        ),
        migrations.CreateModel(
            name="ReportInputField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="Beschreibung"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("char", "Text"),
                            ("int", "Ganzzahl"),
                            ("float", "Dezimalzahl"),
                            ("date", "Datum"),
                            ("bool", "Boolean"),
                            ("list_12months_float", "Dezimalzahlen, 12 Monatswerte"),
                            ("file", "Datei"),
                            ("json", "JSON-Daten"),
                        ],
                        max_length=30,
                        verbose_name="Feldtyp",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "report_type",
                    select2.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.reporttype",
                        verbose_name="Reporttyp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eingabefeld",
                "verbose_name_plural": "Eingabefelder",
                "ordering": ["report_type", "name"],
                "unique_together": {("name", "report_type")},
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
                (
                    "task_id",
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name="Task-ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "Neu"),
                            ("pending", "Wird erstellt..."),
                            ("generated", "Erstellt"),
                            ("generated_dryrun", "Erstellt (Testlauf)"),
                            ("invalid", "Ungültig"),
                        ],
                        default="new",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("state_info", models.TextField(blank=True, verbose_name="Statusinfo")),
                (
                    "report_type",
                    select2.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.reporttype",
                        verbose_name="Reporttyp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "unique_together": {("name", "report_type")},
            },
        ),
        migrations.CreateModel(
            name="ReportOutput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("group", models.CharField(blank=True, max_length=80, verbose_name="Gruppe")),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Datei"),
                            ("csv", "CSV Datei"),
                            ("ods", "ODS Datei"),
                            ("json", "JSON Datei"),
                            ("png", "PNG Datei"),
                            ("text", "Text"),
                        ],
                        max_length=30,
                        verbose_name="Feldtyp",
                    ),
                ),
                ("value", models.TextField(verbose_name="Wert")),
                (
                    "regeneration_json",
                    models.TextField(blank=True, verbose_name="JSON-Daten für neues Erzeugen"),
                ),
                (
                    "report",
                    select2.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.report",
                        verbose_name="Report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reportoutput",
                "verbose_name_plural": "Reportoutputs",
                "unique_together": {("name", "report")},
            },
        ),
        migrations.CreateModel(
            name="ReportInputData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("value", models.TextField(verbose_name="Wert")),
                (
                    "name",
                    select2.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.reportinputfield",
                        verbose_name="Eingabefeld",
                    ),
                ),
                (
                    "report",
                    select2.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.report",
                        verbose_name="Report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eingabewert",
                "verbose_name_plural": "Eingabewerte",
                "unique_together": {("name", "report")},
            },
        ),
    ]
