# Generated by Django 4.2.24 on 2025-10-14 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reporttype",
                verbose_name="Reporttyp",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputdata",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reportinputdata",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportinputfield",
                verbose_name="Eingabefeld",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputdata",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="report.report",
                verbose_name="Report",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("char", "Text"),
                    ("int", "Ganzzahl"),
                    ("float", "Dezimalzahl"),
                    ("date", "Datum"),
                    ("bool", "Boolean"),
                    ("list_12months_float", "Dezimalzahlen, 12 Monatswerte"),
                    ("file", "Datei"),
                    ("json", "JSON-Daten"),
                    ("buildingIds", "Liegenschaften"),
                ],
                max_length=30,
                verbose_name="Feldtyp",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="report_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reporttype",
                verbose_name="Reporttyp",
            ),
        ),
        migrations.AlterField(
            model_name="reportoutput",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reportoutput",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="report.report",
                verbose_name="Report",
            ),
        ),
        migrations.AlterField(
            model_name="reporttype",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
    ]
