# Generated by Django 5.2.16 on 2026-08-17 12:39

import django.db.models.deletion
from django.db import migrations, models

import report.models


# Populate new models/fields
def populate_data(apps, schema_editor):
    ReportInputField = apps.get_model("report", "ReportInputField")
    Report = apps.get_model("report", "Report")
    ReportConfiguration = apps.get_model("report", "ReportConfiguration")
    ReportItemConfiguration = apps.get_model("report", "ReportItemConfiguration")
    ReportItem = apps.get_model("report", "ReportItem")
    ReportInputData = apps.get_model("report", "ReportInputData")

    # Create report_configuration and link to reports + reportitemconfigurations
    config = ReportConfiguration.objects.create(
        name="Migrierte alte Konfiguration", report_type="NK"
    )
    for obj in Report.objects.all():
        obj.report_configuration = config
        obj.save(update_fields=["report_configuration"])

        # Create reportitem per report and link it to report
        item = ReportItem.objects.create(
            name=f"Migriert von Report mit ID {obj.id}", report=obj, item_category="BaseSettings"
        )

        # Link reportinputdata to reportitem
        for input in ReportInputData.objects.filter(report=obj):
            input.item = item
            input.save(update_fields=["item"])

    # Create reportitemconfiguration and link it to report_configuration
    item_config = ReportItemConfiguration.objects.create(
        name="Migrierte alte Konfiguration [Element]",
        report_configuration=config,
        item_category="BaseSettings",
    )

    # Link reportinputfields to item_configuration
    for obj in ReportInputField.objects.all():
        obj.item_configuration = item_config


def populate_data_reverse(apps, schema_editor):
    ReportType = apps.get_model("report", "ReportType")
    report_type = ReportType.objects.first()
    if not report_type:
        report_type = ReportType.objects.create(name="Nebenkostenabrechnung")
    Report = apps.get_model("report", "Report")
    for obj in Report.objects.filter(report_type_OLD__isnull=True):
        obj.report_type_OLD = report_type
        obj.save(update_fields=["report_type_OLD"])
    ReportInputField = apps.get_model("report", "ReportInputField")
    for obj in ReportInputField.objects.filter(report_type_OLD__isnull=True):
        obj.report_type_OLD = report_type
        obj.save(update_fields=["report_type_OLD"])


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0029_alter_invoicecategory_linked_object_type"),
        ("report", "0003_convert_uuids_from_char"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="report_type",
            new_name="report_type_OLD",
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type_OLD",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reporttype",
                verbose_name="Reporttyp (ALT!)",
            ),
        ),
        migrations.RenameField(
            model_name="reportinputfield",
            old_name="report_type",
            new_name="report_type_OLD",
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="report_type_OLD",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reporttype",
                verbose_name="Reporttyp (ALT!)",
            ),
        ),
        migrations.CreateModel(
            name="ReportConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
                (
                    "report_type",
                    models.CharField(
                        choices=[("NK", "Nebenkostenabrechnung")],
                        max_length=30,
                        verbose_name="Reporttyp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report-Konfiguration",
                "verbose_name_plural": "Report-Konfigurationen",
            },
        ),
        migrations.CreateModel(
            name="ReportItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=80, verbose_name="Element-Bezeichnung")),
                (
                    "item_category",
                    models.CharField(
                        choices=[
                            (
                                "PerRentalUnit",
                                "Gebühren nach Mieteinheit und Personen Mindestbelegung",
                            ),
                            ("BaseSettings", "Grundeinstellungen"),
                            (
                                "Standard",
                                "Standard-Nebenkosten (Betrag pro Jahr, verteilt nach Schlüssel)",
                            ),
                            (
                                "Verwaltungsaufwand",
                                "Verwaltungsaufwand als Prozentsatz der Gesamtkosten",
                            ),
                            (
                                "VEWA-Annual",
                                "Wärme/Wasser aufgrund Gesamtkosten und Gesamtverbrauch",
                            ),
                            (
                                "VEWA-AnnualEGON",
                                "Wärme/Wasser aufgrund Gesamtkosten und Verbrauch von EGON",
                            ),
                            ("VEWA-Monthly", "Wärme/Wasser aufgrund Kosten pro Monat"),
                            (
                                "VEWA-MonthlyEGON",
                                "Wärme/Wasser aufgrund Kosten pro Monat und Verbrauch von EGON",
                            ),
                            ("ZEV_Stromallmend", "ZEV-Abrechnung mit dem Stromallmend-Modell"),
                        ],
                        max_length=60,
                        verbose_name="Element-Kategorie",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=report.models.get_next_report_item_order_number,
                        help_text="Order of the item in the report.",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report-Element",
                "verbose_name_plural": "Report-Elemente",
                "ordering": ["report", "order", "item_category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReportItemConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=80, verbose_name="Element-Bezeichnung")),
                (
                    "item_category",
                    models.CharField(
                        choices=[
                            (
                                "PerRentalUnit",
                                "Gebühren nach Mieteinheit und Personen Mindestbelegung",
                            ),
                            ("BaseSettings", "Grundeinstellungen"),
                            (
                                "Standard",
                                "Standard-Nebenkosten (Betrag pro Jahr, verteilt nach Schlüssel)",
                            ),
                            (
                                "Verwaltungsaufwand",
                                "Verwaltungsaufwand als Prozentsatz der Gesamtkosten",
                            ),
                            (
                                "VEWA-Annual",
                                "Wärme/Wasser aufgrund Gesamtkosten und Gesamtverbrauch",
                            ),
                            (
                                "VEWA-AnnualEGON",
                                "Wärme/Wasser aufgrund Gesamtkosten und Verbrauch von EGON",
                            ),
                            ("VEWA-Monthly", "Wärme/Wasser aufgrund Kosten pro Monat"),
                            (
                                "VEWA-MonthlyEGON",
                                "Wärme/Wasser aufgrund Kosten pro Monat und Verbrauch von EGON",
                            ),
                            ("ZEV_Stromallmend", "ZEV-Abrechnung mit dem Stromallmend-Modell"),
                        ],
                        max_length=60,
                        verbose_name="Element-Kategorie",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=report.models.get_next_report_item_configuration_order_number,
                        help_text="Order of the item in the report.",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report-Element-Konfiguration",
                "verbose_name_plural": "Report-Element-Konfigurationen",
                "ordering": ["report_configuration", "order", "item_category", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="reportinputdata",
            options={
                "ordering": ["report", "name__item_configuration", "order", "description"],
                "verbose_name": "Eingabewert",
                "verbose_name_plural": "Eingabewerte",
            },
        ),
        migrations.AlterModelOptions(
            name="reportinputfield",
            options={
                "ordering": ["item_configuration", "order", "name"],
                "verbose_name": "Eingabefeld",
                "verbose_name_plural": "Eingabefelder",
            },
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reportinputdata",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reportinputfield",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reportoutput",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="report",
            name="show_full_config",
            field=models.BooleanField(
                default=False, verbose_name="Expert:innen-Konfiguration anzeigen"
            ),
        ),
        migrations.AddField(
            model_name="reportinputdata",
            name="description",
            field=models.CharField(blank=True, max_length=200, verbose_name="Beschreibung"),
        ),
        migrations.AddField(
            model_name="reportinputdata",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("char", "Text"),
                    ("int", "Ganzzahl"),
                    ("float", "Dezimalzahl"),
                    ("date", "Datum"),
                    ("bool", "Boolean"),
                    ("list_12months_float", "Dezimalzahlen, 12 Monatswerte"),
                    ("file", "Datei"),
                    ("json", "JSON-Daten"),
                    ("buildingIds", "Liegenschaften"),
                    ("enum_vewa_category", "VEWA Kategorie"),
                    ("enum_monthly_weights", "Verteilschlssel nach Monat"),
                    ("enum_section_weights", "Verteilschlüssel nach Objekttyp"),
                    ("enum_object_weights", "Verteilschlüssel nach Objekt"),
                ],
                default="char",
                max_length=60,
                verbose_name="Feldtyp",
            ),
        ),
        migrations.AddField(
            model_name="reportinputdata",
            name="order",
            field=models.IntegerField(
                default=50, help_text="Order of the field.", verbose_name="Order"
            ),
        ),
        migrations.AddField(
            model_name="reportinputdata",
            name="show",
            field=models.BooleanField(
                default=False,
                help_text="Falls aktiv, wird das Eingabefeld angezeigt.",
                verbose_name="Anzeigen",
            ),
        ),
        migrations.AddField(
            model_name="reportinputfield",
            name="order",
            field=models.IntegerField(
                default=report.models.get_next_report_input_field_order_number,
                help_text="Order of the field.",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="reportinputfield",
            name="show",
            field=models.BooleanField(
                default=False,
                help_text="Falls aktiv, wird das Eingabefeld für die Erstellung des Reports angezeigt, andernfalls wird der Standardwert von hier verwendet.",
                verbose_name="Anzeigen",
            ),
        ),
        migrations.AddField(
            model_name="reportinputfield",
            name="value_default",
            field=models.CharField(blank=True, max_length=6000, verbose_name="Standardwert"),
        ),
        migrations.AlterField(
            model_name="reportinputdata",
            name="value",
            field=models.CharField(blank=True, max_length=6000, verbose_name="Wert"),
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("char", "Text"),
                    ("int", "Ganzzahl"),
                    ("float", "Dezimalzahl"),
                    ("date", "Datum"),
                    ("bool", "Boolean"),
                    ("list_12months_float", "Dezimalzahlen, 12 Monatswerte"),
                    ("file", "Datei"),
                    ("json", "JSON-Daten"),
                    ("buildingIds", "Liegenschaften"),
                    ("enum_vewa_category", "VEWA Kategorie"),
                    ("enum_monthly_weights", "Verteilschlssel nach Monat"),
                    ("enum_section_weights", "Verteilschlüssel nach Objekttyp"),
                    ("enum_object_weights", "Verteilschlüssel nach Objekt"),
                ],
                max_length=60,
                verbose_name="Feldtyp",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportoutput",
            constraint=models.UniqueConstraint(
                fields=("name", "report"), name="unique_report_output"
            ),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="buildings",
            field=models.ManyToManyField(
                blank=True, to="geno.building", verbose_name="Liegenschaften"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="report_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportconfiguration",
                verbose_name="Report-Konfiguration",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("name", "report_configuration"), name="unique_report"
            ),
        ),
        migrations.AddField(
            model_name="reportitem",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.report",
                verbose_name="Report",
            ),
        ),
        migrations.AddField(
            model_name="reportinputdata",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportitem",
                verbose_name="Report-Element",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportinputdata",
            constraint=models.UniqueConstraint(
                fields=("name", "report"), name="unique_report_input_data"
            ),
        ),
        migrations.AddField(
            model_name="reportitemconfiguration",
            name="report_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportconfiguration",
                verbose_name="Report-Konfiguration",
            ),
        ),
        migrations.AddField(
            model_name="reportinputfield",
            name="item_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportitemconfiguration",
                verbose_name="Report-Element",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportinputfield",
            constraint=models.UniqueConstraint(
                fields=("name", "item_configuration"), name="unique_report_input_field"
            ),
        ),
        migrations.RemoveField(
            model_name="reportinputfield",
            name="active",
        ),
        migrations.AddConstraint(
            model_name="reportitem",
            constraint=models.UniqueConstraint(
                fields=("name", "item_category", "report"), name="unique_report_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportitemconfiguration",
            constraint=models.UniqueConstraint(
                fields=("name", "item_category", "report_configuration"),
                name="unique_report_configuration_item",
            ),
        ),
        migrations.RunPython(populate_data, populate_data_reverse),
        ## Remove null=True after migrating data
        migrations.AlterField(
            model_name="report",
            name="report_configuration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportconfiguration",
                verbose_name="Report-Konfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="reportitem",
            name="report",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.report",
                verbose_name="Report",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputdata",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportitem",
                verbose_name="Report-Element",
            ),
        ),
        migrations.AlterField(
            model_name="reportitemconfiguration",
            name="report_configuration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportconfiguration",
                verbose_name="Report-Konfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="item_configuration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportitemconfiguration",
                verbose_name="Report-Element",
            ),
        ),
        migrations.RemoveField(
            model_name="report",
            name="report_type_OLD",
        ),
        migrations.RemoveField(
            model_name="reportinputfield",
            name="report_type_OLD",
        ),
        migrations.DeleteModel(
            name="ReportType",
        ),
    ]
