# Generated by Django 4.2.29 on 2026-03-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_reportinputfield_value_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='report_configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.reportconfiguration', verbose_name='Report-Konfiguration'),
        ),
        migrations.AlterField(
            model_name='reportinputfield',
            name='item_configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_item_configuration', to='report.reportitemconfiguration', verbose_name='Report-Element'),
        ),
        migrations.AlterField(
            model_name='reportitemconfiguration',
            name='report_configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_configuration', to='report.reportconfiguration', verbose_name='Report-Konfiguration'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('name', 'report_configuration')},
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Kommentar')),
                ('ts_created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('ts_modified', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('name', models.CharField(max_length=80, verbose_name='Element-Bezeichnung')),
                ('item_category', models.CharField(choices=[('SHORT', 'Name')], max_length=30, verbose_name='Element-Kategorie')),
                ('report_configuration', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='report.report', verbose_name='Report-Konfiguration')),
            ],
            options={
                'verbose_name': 'Report-Element',
                'verbose_name_plural': 'Report-Elemente',
                'ordering': ['item_category', 'name'],
                'unique_together': {('name', 'item_category')},
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AddField(
            model_name='reportinputdata',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_item', to='report.reportitem', verbose_name='Report-Element'),
        ),
    ]
