# Generated by Django 4.2.29 on 2026-05-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='item_category',
            field=models.CharField(choices=[('Hauswartung_ServiceHeizungLüftung', 'Hauswartung (Service, Heizung, Lüftung)'), ('Reinigung', 'Reinigung'), ('Umgebung_Siedlung', 'Umgebung/Siedlungspflege'), ('Betriebskosten_Gemeinschaft', 'Betriebskosten Gemeinschaftsanlagen'), ('Winterdienst', 'Winterdienst'), ('Lift', 'Lift'), ('Kehrichtgebuehren', 'Kehrichtgebühren'), ('Fernwaerme_Warmwasser', 'Fernwärme: Warmwasser'), ('Fernwaerme_Fussboden', 'Fernwärme: Fussbodenheizung'), ('Fernwaerme_Radiatoren', 'Fernwärme: Radiatoren'), ('Fernwaerme_Lueftung', 'Fernwärme: Lüftung'), ('Wasser_Abwasser', 'Wasser/Abwasser'), ('Strom_Total', 'Stromkosten'), ('Internet/WLAN', 'Internet/WLAN')], max_length=60, verbose_name='Element-Kategorie'),
        ),
        migrations.AlterField(
            model_name='reportitemconfiguration',
            name='item_category',
            field=models.CharField(choices=[('Hauswartung_ServiceHeizungLüftung', 'Hauswartung (Service, Heizung, Lüftung)'), ('Reinigung', 'Reinigung'), ('Umgebung_Siedlung', 'Umgebung/Siedlungspflege'), ('Betriebskosten_Gemeinschaft', 'Betriebskosten Gemeinschaftsanlagen'), ('Winterdienst', 'Winterdienst'), ('Lift', 'Lift'), ('Kehrichtgebuehren', 'Kehrichtgebühren'), ('Fernwaerme_Warmwasser', 'Fernwärme: Warmwasser'), ('Fernwaerme_Fussboden', 'Fernwärme: Fussbodenheizung'), ('Fernwaerme_Radiatoren', 'Fernwärme: Radiatoren'), ('Fernwaerme_Lueftung', 'Fernwärme: Lüftung'), ('Wasser_Abwasser', 'Wasser/Abwasser'), ('Strom_Total', 'Stromkosten'), ('Internet/WLAN', 'Internet/WLAN')], max_length=60, verbose_name='Element-Kategorie'),
        ),
    ]
