# Generated by Django 4.2.29 on 2026-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_reportitem_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinputfield',
            name='field_type',
            field=models.CharField(choices=[('char', 'Text'), ('int', 'Ganzzahl'), ('float', 'Dezimalzahl'), ('date', 'Datum'), ('bool', 'Boolean'), ('list_12months_float', 'Dezimalzahlen, 12 Monatswerte'), ('file', 'Datei'), ('json', 'JSON-Daten'), ('buildingIds', 'Liegenschaften')], max_length=60, verbose_name='Feldtyp'),
        ),
        migrations.AlterField(
            model_name='reportinputfield',
            name='value_default',
            field=models.CharField(blank=True, max_length=6000, verbose_name='Standardwert'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='item_category',
            field=models.CharField(choices=[('Betriebskosten_Gemeinschaft', 'Betriebskosten Gemeinschaftsanlagen'), ('Fernwaerme_Fussboden', 'Fernwärme: Fussbodenheizung'), ('Fernwaerme_Lueftung', 'Fernwärme: Lüftung'), ('Fernwaerme_Radiatoren', 'Fernwärme: Radiatoren'), ('Fernwaerme_Warmwasser', 'Fernwärme: Warmwasser'), ('Hauswartung_ServiceHeizungLüftung', 'Hauswartung (Service, Heizung, Lüftung)'), ('Internet/WLAN', 'Internet/WLAN'), ('Kehrichtgebuehren', 'Kehrichtgebühren'), ('Lift', 'Lift'), ('Reinigung', 'Reinigung'), ('Strom_Total', 'Stromkosten'), ('Umgebung_Siedlung', 'Umgebung/Siedlungspflege'), ('Wasser_Abwasser', 'Wasser/Abwasser'), ('Winterdienst', 'Winterdienst')], max_length=60, verbose_name='Element-Kategorie'),
        ),
        migrations.AlterField(
            model_name='reportitemconfiguration',
            name='item_category',
            field=models.CharField(choices=[('Betriebskosten_Gemeinschaft', 'Betriebskosten Gemeinschaftsanlagen'), ('Fernwaerme_Fussboden', 'Fernwärme: Fussbodenheizung'), ('Fernwaerme_Lueftung', 'Fernwärme: Lüftung'), ('Fernwaerme_Radiatoren', 'Fernwärme: Radiatoren'), ('Fernwaerme_Warmwasser', 'Fernwärme: Warmwasser'), ('Hauswartung_ServiceHeizungLüftung', 'Hauswartung (Service, Heizung, Lüftung)'), ('Internet/WLAN', 'Internet/WLAN'), ('Kehrichtgebuehren', 'Kehrichtgebühren'), ('Lift', 'Lift'), ('Reinigung', 'Reinigung'), ('Strom_Total', 'Stromkosten'), ('Umgebung_Siedlung', 'Umgebung/Siedlungspflege'), ('Wasser_Abwasser', 'Wasser/Abwasser'), ('Winterdienst', 'Winterdienst')], max_length=60, verbose_name='Element-Kategorie'),
        ),
    ]
