# Generated by Django 4.2.29 on 2026-05-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_reportinputfield_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinputdata',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='reportinputdata',
            name='field_type',
            field=models.CharField(choices=[('char', 'Text'), ('int', 'Ganzzahl'), ('float', 'Dezimalzahl'), ('date', 'Datum'), ('bool', 'Boolean'), ('list_12months_float', 'Dezimalzahlen, 12 Monatswerte'), ('file', 'Datei'), ('json', 'JSON-Daten'), ('buildingIds', 'Liegenschaften')], default='char', max_length=60, verbose_name='Feldtyp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportinputdata',
            name='value',
            field=models.CharField(blank=True, max_length=6000, verbose_name='Wert'),
        ),
    ]
