# Generated by Django 4.2.30 on 2026-08-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0008_reportinputdata_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportitem",
            old_name="report_configuration",
            new_name="report",
        ),
        migrations.AlterField(
            model_name="reportitem",
            name="report",
            field=models.ForeignKey(
                default=1,
                on_delete=models.deletion.CASCADE,
                to="report.report",
                verbose_name="Report",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputdata",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=models.deletion.CASCADE,
                to="report.reportitem",
                verbose_name="Report-Element",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="item_configuration",
            field=models.ForeignKey(
                default=1,
                on_delete=models.deletion.CASCADE,
                to="report.reportitemconfiguration",
                verbose_name="Report-Element",
            ),
        ),
        migrations.AlterField(
            model_name="reportitemconfiguration",
            name="report_configuration",
            field=models.ForeignKey(
                default=1,
                on_delete=models.deletion.CASCADE,
                to="report.reportconfiguration",
                verbose_name="Report-Konfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputdata",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("char", "Text"),
                    ("int", "Ganzzahl"),
                    ("float", "Dezimalzahl"),
                    ("date", "Datum"),
                    ("bool", "Boolean"),
                    ("list_12months_float", "Dezimalzahlen, 12 Monatswerte"),
                    ("file", "Datei"),
                    ("json", "JSON-Daten"),
                    ("buildingIds", "Liegenschaften"),
                    ("enum_vewa_category", "VEWA Kategorie"),
                    ("enum_monthly_weights", "Verteilschlssel nach Monat"),
                    ("enum_section_weights", "Verteilschlüssel nach Objekttyp"),
                    ("enum_object_weights", "Verteilschlüssel nach Objekt"),
                ],
                max_length=60,
                verbose_name="Feldtyp",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("char", "Text"),
                    ("int", "Ganzzahl"),
                    ("float", "Dezimalzahl"),
                    ("date", "Datum"),
                    ("bool", "Boolean"),
                    ("list_12months_float", "Dezimalzahlen, 12 Monatswerte"),
                    ("file", "Datei"),
                    ("json", "JSON-Daten"),
                    ("buildingIds", "Liegenschaften"),
                    ("enum_vewa_category", "VEWA Kategorie"),
                    ("enum_monthly_weights", "Verteilschlssel nach Monat"),
                    ("enum_section_weights", "Verteilschlüssel nach Objekttyp"),
                    ("enum_object_weights", "Verteilschlüssel nach Objekt"),
                ],
                max_length=60,
                verbose_name="Feldtyp",
            ),
        ),
        migrations.AlterField(
            model_name="reportitem",
            name="item_category",
            field=models.CharField(
                choices=[
                    ("PerRentalUnit", "Gebühren nach Mieteinheit und Personen Mindestbelegung"),
                    ("BaseSettings", "Grundeinstellungen"),
                    (
                        "Standard",
                        "Standard-Nebenkosten (Betrag pro Jahr, verteilt nach Schlüssel)",
                    ),
                    ("Verwaltungsaufwand", "Verwaltungsaufwand als Prozentsatz der Gesamtkosten"),
                    ("VEWA-Annual", "Wärme/Wasser aufgrund Gesamtkosten und Gesamtverbrauch"),
                    (
                        "VEWA-AnnualEGON",
                        "Wärme/Wasser aufgrund Gesamtkosten und Verbrauch von EGON",
                    ),
                    ("VEWA-Monthly", "Wärme/Wasser aufgrund Kosten pro Monat"),
                    (
                        "VEWA-MonthlyEGON",
                        "Wärme/Wasser aufgrund Kosten pro Monat und Verbrauch von EGON",
                    ),
                    ("ZEV_Stromallmend", "ZEV-Abrechnung mit dem Stromallmend-Modell"),
                ],
                max_length=60,
                verbose_name="Element-Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="reportitemconfiguration",
            name="item_category",
            field=models.CharField(
                choices=[
                    ("PerRentalUnit", "Gebühren nach Mieteinheit und Personen Mindestbelegung"),
                    ("BaseSettings", "Grundeinstellungen"),
                    (
                        "Standard",
                        "Standard-Nebenkosten (Betrag pro Jahr, verteilt nach Schlüssel)",
                    ),
                    ("Verwaltungsaufwand", "Verwaltungsaufwand als Prozentsatz der Gesamtkosten"),
                    ("VEWA-Annual", "Wärme/Wasser aufgrund Gesamtkosten und Gesamtverbrauch"),
                    (
                        "VEWA-AnnualEGON",
                        "Wärme/Wasser aufgrund Gesamtkosten und Verbrauch von EGON",
                    ),
                    ("VEWA-Monthly", "Wärme/Wasser aufgrund Kosten pro Monat"),
                    (
                        "VEWA-MonthlyEGON",
                        "Wärme/Wasser aufgrund Kosten pro Monat und Verbrauch von EGON",
                    ),
                    ("ZEV_Stromallmend", "ZEV-Abrechnung mit dem Stromallmend-Modell"),
                ],
                max_length=60,
                verbose_name="Element-Kategorie",
            ),
        ),
    ]
