# Generated by Django 4.2.30 on 2026-08-07 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0009_rename_report_configuration_reportitem_report_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reportitem",
            unique_together={("name", "item_category", "report")},
        ),
        migrations.AlterUniqueTogether(
            name="reportitemconfiguration",
            unique_together={("name", "item_category", "report_configuration")},
        ),
    ]
