# Generated by Django 4.2.30 on 2026-08-14 17:33

from django.db import migrations, models

import report.models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0010_alter_reportitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportitem",
            options={
                "ordering": ["report", "order", "item_category", "name"],
                "verbose_name": "Report-Element",
                "verbose_name_plural": "Report-Elemente",
            },
        ),
        migrations.AlterModelOptions(
            name="reportitemconfiguration",
            options={
                "ordering": ["report_configuration", "order", "item_category", "name"],
                "verbose_name": "Report-Element-Konfiguration",
                "verbose_name_plural": "Report-Element-Konfigurationen",
            },
        ),
        migrations.AlterUniqueTogether(
            name="reportitem",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reportitemconfiguration",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reportitem",
            name="order",
            field=models.IntegerField(
                default=report.models.get_next_report_item_order_number,
                help_text="Order of the item in the report.",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="reportitemconfiguration",
            name="order",
            field=models.IntegerField(
                default=report.models.get_next_report_item_configuration_order_number,
                help_text="Order of the item in the report.",
                verbose_name="Order",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportitem",
            constraint=models.UniqueConstraint(
                fields=("name", "item_category", "report"), name="unique_report_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportitemconfiguration",
            constraint=models.UniqueConstraint(
                fields=("name", "item_category", "report_configuration"),
                name="unique_report_configuration_item",
            ),
        ),
    ]
