# Generated by Django 4.2.30 on 2026-08-14 22:33

from django.db import migrations, models

import report.models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0011_alter_reportitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportinputdata",
            options={
                "ordering": ["report", "name__item_configuration", "order", "description"],
                "verbose_name": "Eingabewert",
                "verbose_name_plural": "Eingabewerte",
            },
        ),
        migrations.AlterModelOptions(
            name="reportinputfield",
            options={
                "ordering": ["item_configuration", "order", "name"],
                "verbose_name": "Eingabefeld",
                "verbose_name_plural": "Eingabefelder",
            },
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reportinputdata",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reportinputfield",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reportoutput",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reportinputdata",
            name="order",
            field=models.IntegerField(
                default=50, help_text="Order of the field.", verbose_name="Order"
            ),
        ),
        migrations.AddField(
            model_name="reportinputfield",
            name="order",
            field=models.IntegerField(
                default=report.models.get_next_report_input_field_order_number,
                help_text="Order of the field.",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Falls aktiv, wird das Eingabefeld für die Erstellung des Reports angezeigt, andernfalls wird der Standardwert von hier verwendet.",
                verbose_name="Eingabe",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("name", "report_configuration"), name="unique_report"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportinputdata",
            constraint=models.UniqueConstraint(
                fields=("name", "report"), name="unique_report_input_data"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportinputfield",
            constraint=models.UniqueConstraint(
                fields=("name", "item_configuration"), name="unique_report_input_field"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportoutput",
            constraint=models.UniqueConstraint(
                fields=("name", "report"), name="unique_report_output"
            ),
        ),
    ]
