# Generated by Django 4.2.30 on 2026-08-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0012_alter_reportinputdata_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportinputfield",
            old_name="active",
            new_name="show",
        ),
        migrations.AddField(
            model_name="reportinputdata",
            name="show",
            field=models.BooleanField(
                default=False,
                help_text="Falls aktiv, wird das Eingabefeld angezeigt.",
                verbose_name="Anzeigen",
            ),
        ),
        migrations.AlterField(
            model_name="reportinputfield",
            name="show",
            field=models.BooleanField(
                default=False,
                help_text="Falls aktiv, wird das Eingabefeld für die Erstellung des Reports angezeigt, andernfalls wird der Standardwert von hier verwendet.",
                verbose_name="Anzeigen",
            ),
        ),
    ]
