# Generated by Django 4.2.30 on 2026-08-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0013_rename_active_reportinputfield_show_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="show_full_config",
            field=models.BooleanField(
                default=False, verbose_name="Expert:innen-Konfiguration anzeigen"
            ),
        ),
    ]
