# Generated by Django 4.2.21 on 2025-08-22 16:58

import django.db.models.deletion
import select2.fields
from django.db import migrations, models

from geno import settings as geno_settings


def init_data(apps, schema_editor):
    CONTENTTEMPLATEOPTION_NAME_CHOICES = (
        ("share_statement_context", "Kontoauszug-Felder verwenden"),
        ("billing_context", "Rechnungsstellung-Felder verwenden"),
        ("qrbill_account", "IBAN für QR-Rechnung"),
        ("qrbill_invoice_type_id", "QR-Kategorie-Code für Ref.Nr."),
        ("qrbill_info", "QR-Infotext"),
        ("qrbill_rental_unit_in_extra_info", "Mietobj. bei QR-Infotext anfügen"),
        ("bill_text_default", "Standard-Rechnungstext"),
        ("bill_amount_default", "Standard-Rechnungsbetrag"),
        ("bill_text_memberflag_01", f"Rechnungstext für {geno_settings.MEMBER_FLAGS[1]}"),
        ("bill_amount_memberflag_01", f"Rechnungsbetrag für {geno_settings.MEMBER_FLAGS[1]}"),
        ("bill_text_memberflag_02", f"Rechnungstext für {geno_settings.MEMBER_FLAGS[2]}"),
        ("bill_amount_memberflag_02", f"Rechnungsbetrag für {geno_settings.MEMBER_FLAGS[2]}"),
        ("bill_text_memberflag_03", f"Rechnungstext für {geno_settings.MEMBER_FLAGS[3]}"),
        ("bill_amount_memberflag_03", f"Rechnungsbetrag für {geno_settings.MEMBER_FLAGS[3]}"),
        ("bill_text_memberflag_04", f"Rechnungstext für {geno_settings.MEMBER_FLAGS[4]}"),
        ("bill_amount_memberflag_04", f"Rechnungsbetrag für {geno_settings.MEMBER_FLAGS[4]}"),
        ("bill_text_memberflag_05", f"Rechnungstext für {geno_settings.MEMBER_FLAGS[5]}"),
        ("bill_amount_memberflag_05", f"Rechnungsbetrag für {geno_settings.MEMBER_FLAGS[5]}"),
        ("share_count_context_var", "Variablenname für Anz. Beteiligungen"),
        ("share_count_sharetype", "Beteiligungstyp für Anz. Beteiligungen"),
    )
    type_model = apps.get_model("geno", "contenttemplateoptiontype")
    for opt in CONTENTTEMPLATEOPTION_NAME_CHOICES:
        type_model.objects.create(name=opt[0], description=opt[1])


def migrate_options(apps, schema_editor):
    opt_model = apps.get_model("geno", "contenttemplateoption")
    type_model = apps.get_model("geno", "contenttemplateoptiontype")
    for opt in opt_model.objects.all():
        opt.name_new = type_model.objects.get(name=opt.name)
        opt.save()


def migrate_options_reverse(apps, schema_editor):
    opt_model = apps.get_model("geno", "contenttemplateoption")
    for opt in opt_model.objects.all():
        opt.name = opt.name_new.name
        opt.save()


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTemplateOptionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                ("description", models.CharField(max_length=200, verbose_name="Bezeichung")),
            ],
            options={
                "verbose_name": "Vorlagenoptionentyp",
                "verbose_name_plural": "Vorlagenoptionentypen",
            },
        ),
        migrations.RunPython(init_data, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="contenttemplateoption",
            name="name_new",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.contenttemplateoptiontype",
                verbose_name="Variable",
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_options, reverse_code=migrate_options_reverse),
        migrations.RemoveField(
            model_name="contenttemplateoption",
            name="name",
        ),
        migrations.RenameField(
            model_name="contenttemplateoption",
            old_name="name_new",
            new_name="name",
        ),
    ]
