# Generated by Django 4.2.24 on 2025-09-29 14:05

import select2.fields

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0003_shareattatchbuilding'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='main_contract',
            field=select2.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_contract', to='geno.contract', verbose_name='Hauptvertrag'),
        ),
    ]
