# Generated by Django 4.2.24 on 2025-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0004_rentalunitrentnetto'),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="telephoneOffice2",
            field=models.CharField(blank=True, max_length=30, verbose_name="2. Telefon Geschäft"),
        ),
        migrations.AddField(
            model_name="address",
            name="telephoneOffice",
            field=models.CharField(blank=True, max_length=30, verbose_name="Telefon Geschäft"),
        ),
        migrations.AddField(
            model_name="address",
            name="website",
            field=models.CharField(blank=True, max_length=300, verbose_name="Webseite"),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="rent_netto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="exkl. NK+Strom",
                max_digits=10,
                null=True,
                verbose_name="Netto-Miete (Fr.)",
            ),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="import_id",
            field=models.IntegerField(
                blank=True, default=None, null=True, unique=True, verbose_name="Import-ID"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="city_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ort"),
        ),
        migrations.AddField(
            model_name="building",
            name="city_zipcode",
            field=models.CharField(blank=True, max_length=30, verbose_name="PLZ"),
        ),
        migrations.AddField(
            model_name="building",
            name="country",
            field=models.CharField(
                blank=True, default="Schweiz", max_length=100, verbose_name="Land"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="egid",
            field=models.PositiveIntegerField(null=True, verbose_name="EGID"),
        ),
        migrations.AddField(
            model_name="building",
            name="house_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="Hausnummer"),
        ),
        migrations.AddField(
            model_name="building",
            name="street_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Strasse"),
        ),
        migrations.AddField(
            model_name="building",
            name="value_build",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Anlagekosten (Fr.)",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="value_insurance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Gebäudeversicherungswert (Fr.)",
            ),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="ewid",
            field=models.PositiveIntegerField(null=True, verbose_name="EWID"),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="internal_nr",
            field=models.PositiveIntegerField(null=True, verbose_name="Interne-Nummer"),
        ),
    ]
