# Generated by Django 4.2.24 on 2025-10-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0004_bankaccount_alter_address_bankaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='bankaccount',
            new_name='bankaccount_id',
        ),
    ]
