# Generated by Django 4.2.24 on 2025-10-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0005_rename_bankaccount_address_bankaccount_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='bankaccount_id',
            new_name='bankaccount',
        ),
    ]
