# Generated by Django 4.2.24 on 2025-09-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0005_contract_main_contract'),
    ]

    operations = [migrations.RunSQL("""CREATE VIEW geno_TenantsView AS
SELECT DISTINCT
	CONVERT(concat(LPAD(c.id, 4, 0), LPAD(bu.id, 4, 0), LPAD(ru.id, 4, 0), LPAD(ad.id, 4,0)), INTEGER) as id,
	'' as comment,
    bu.name as bu_name,
    ru.name as ru_name,
    ru.rental_type as ru_type,
    ru.label as ru_label,
    ru.floor as ru_floor,
    ru.area as ru_area,
    ru.rooms as ru_rooms,
    ad.organization as organization,
    ad.name as ad_name,
    ad.first_name as ad_first_name,
    ad.title as ad_title,
    ad.email as ad_email,
    0 as c_ischild,
    NULL as c_age,
    NULL as presence,
    ad.date_birth as ad_date_birth,
    concat(ad.city_zipcode, ' ', ad.city_name) as ad_city,
    concat(ad.street_name, ' ', ad.house_number) as ad_street,
    ad.telephone as ad_tel1,
    ad.mobile as ad_tel2,
    ad.hometown as p_hometown,
    ad.occupation as p_occupation,
    m.date_join as p_membership_date,
    bu.id as building_id,
    ru.id as rental_unit_id,
    c.isSC as c_isSubcontract,
    c.id as contract_id,
    c.ts_created,
    c.ts_modified
FROM
    (select ctmp.*, 0 as isSC from geno_contract ctmp UNION select sctmp.*, 1 as isSC from geno_contract ctmp JOIN geno_contract sctmp ON ctmp.id = sctmp.main_contract_id) as c
LEFT JOIN
    geno_contract_rental_units cru ON cru.contract_id = c.id
LEFT JOIN
    geno_rentalunit ru ON ru.id = cru.rentalunit_id
LEFT JOIN
    geno_building bu ON bu.id = ru.building_id
LEFT JOIN
    geno_contract_contractors ccon ON ccon.contract_id = c.id
LEFT JOIN
    geno_address ad ON ccon.address_id = ad.id
LEFT JOIN
    geno_member m ON m.name_id = ad.id
UNION
SELECT DISTINCT
	CONVERT(concat(LPAD(c.id, 4, 0), LPAD(bu.id, 4, 0), LPAD(ru.id, 4, 0), LPAD(ad.id, 4,0)), INTEGER) as id,
	'' as comment,
    bu.name as bu_name,
    ru.name as ru_name,
    ru.rental_type as ru_type,
    ru.label as ru_label,
    ru.floor as ru_floor,
    ru.area as ru_area,
    ru.rooms as ru_rooms,
    ad.organization as organization,
    ad.name as ad_name,
    ad.first_name as ad_first_name,
    ad.title as ad_title,
    ad.email as ad_email,
    1 as c_ischild,
    TIMESTAMPDIFF(YEAR, ad.date_birth, CURDATE()) as c_age,
    ch.presence as presence,
    ad.date_birth as ad_date_birth,
    concat(ad.city_zipcode, ' ', ad.city_name) as ad_city,
    concat(ad.street_name, ' ', ad.house_number) as ad_street,
    ad.telephone as ad_tel1,
    ad.mobile as ad_tel2,
    ad.hometown as p_hometown,
    ad.occupation as p_occupation,
    m.date_join as p_membership_date,
    bu.id as building_id,
    ru.id as rental_unit_id,
    c.isSC as c_isSubcontract,
    c.id as contract_id,
    c.ts_created,
    c.ts_modified
FROM
    (select ctmp.*, 0 as isSC from geno_contract ctmp UNION select sctmp.*, 1 as isSC from geno_contract ctmp JOIN geno_contract sctmp ON ctmp.id = sctmp.main_contract_id) as c
LEFT JOIN
    geno_contract_rental_units cru ON cru.contract_id = c.id
LEFT JOIN
    geno_rentalunit ru ON ru.id = cru.rentalunit_id
LEFT JOIN
    geno_building bu ON bu.id = ru.building_id
JOIN
    geno_contract_children cc ON cc.contract_id = c.id
LEFT JOIN
    geno_child ch ON cc.child_id = ch.id
LEFT JOIN
    geno_address ad ON ad.id = ch.name_id
LEFT JOIN
    geno_member m ON m.name_id = ad.id;""", """DROP VIEW geno_TenantsView;""")]
