# Generated by Django 4.2.24 on 2025-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0007_address_building_extension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="emonitor_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Import-ID",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="emonitor_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Import-ID",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="emonitor_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Import-ID",
            ),
        ),
        migrations.RenameField(
            model_name="address",
            old_name="emonitor_id",
            new_name="import_id",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="emonitor_id",
            new_name="import_id",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="emonitor_id",
            new_name="import_id",
        ),
    ]
