# Generated by Django 4.2.24 on 2025-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0008_migrate_emonitor2import'),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalunit",
            name="nk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Wird bei unvermieteten Gewerberäumen auch auf der Website angezeigt.",
                max_digits=10,
                null=True,
                verbose_name="Nebenkosten Akonto (Fr.)",
            ),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="nk_flat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Nebenkosten Pauschal (Fr.)",
            ),
        ),
    ]
