# Generated by Django 4.2.24 on 2025-09-29 14:56

import django.db.models.deletion
from django.db import migrations, models
from stdnum import iban as iban_util


def migrate_bank_accounts(apps, schema_editor):
    address = apps.get_model("geno", "Address")
    contract = apps.get_model("geno", "Contract")
    bank_account = apps.get_model("geno", "BankAccount")

    # Migrate address
    for add in address.objects.exclude(bank_account=""):
        bankaccount_string = add.bankaccount
        iban_parsed = parse_iban_field(bankaccount_string)
        if iban_parsed[0] == "valid_iban_with_bank":
            bank, created = bank_account.objects.get_or_create(
                iban=iban_parsed[1], finanzinstitut=iban_parsed[2]
            )
            add.bankaccount = bank.id
        elif iban_parsed[0] == "valid_iban":
            bank, created = bank_account.objects.get_or_create(iban=iban_parsed[1])
            add.bankaccount = bank.id
        else:
            bank = bank_account.objects.create(comment=bankaccount_string)
            add.bankaccount = bank.id
        add.save()

    # Migrate contract
    for cont in contract.objects.exclude(bank_account=""):
        bankaccount_string = cont.bankaccount
        iban_parsed = parse_iban_field(bankaccount_string)
        if iban_parsed[0] == "valid_iban_with_bank":
            bank, created = bank_account.objects.get_or_create(
                iban=iban_parsed[1], finanzinstitut=iban_parsed[2]
            )
            cont.bankaccount = bank.id
        elif iban_parsed[0] == "valid_iban":
            bank, created = bank_account.objects.get_or_create(iban=iban_parsed[1])
            cont.bankaccount = bank.id
        elif iban_parsed[0] == "other" and bankaccount_string == "":
            bank = bank_account.objects.create(comment="")
            cont.bankaccount = bank.id
        elif iban_parsed[0] == "other" and bankaccount_string != "":
            bank, created = bank_account.objects.get_or_create(comment=bankaccount_string)
            cont.bankaccount = bank.id
        cont.save()


def reverse_migrate_bank_accounts(apps, schema_editor):
    address = apps.get_model("geno", "Address")
    contract = apps.get_model("geno", "Contract")
    bank_account = apps.get_model("geno", "BankAccount")

    # Reverse for address
    for add in address.objects.all():
        if add.bankaccount:
            bank = bank_account.objects.get(id=add.bankaccount)
            if bank.iban:
                value = bank.iban
                if bank.finanzinstitut:
                    value = f"{value}, {bank.finanzinstitut}"
            else:
                value = bank.comment
            add.bankaccount = value
            add.save()

    # Reverse for contract
    for cont in contract.objects.all():
        if cont.bankaccount:
            bank = bank_account.objects.get(id=cont.bankaccount)
            if bank.iban:
                value = bank.iban
                if bank.finanzinstitut:
                    value = f"{value}, {bank.finanzinstitut}"
            else:
                value = bank.comment
            cont.bankaccount = value
            cont.save()
    # Remove all BankAccount objects
    bank_account.objects.all().delete()
    migrations.DeleteModel(name="BankAccount")


def parse_iban_field(value):
    if not value:
        return "other", None, None

    parts = [p.strip() for p in value.split(",", 1)]
    iban_part = parts[0]
    bank_name = parts[1] if len(parts) > 1 else None

    if iban_util.is_valid(iban_part):
        if bank_name:
            return "valid_iban_with_bank", iban_part, bank_name
        else:
            return "valid_iban", iban_part, None
    else:
        return "other", value, None


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0008_migrate_emonitor2import"),
    ]
    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("iban", models.CharField(blank=True, max_length=34, verbose_name="IBAN")),
                (
                    "finanzinstitut",
                    models.CharField(blank=True, max_length=100, verbose_name="Finanzinstitut"),
                ),
                (
                    "kontoinhaber",
                    models.CharField(blank=True, max_length=100, verbose_name="Kontoinhaber"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(migrate_bank_accounts, reverse_migrate_bank_accounts),
        migrations.AlterField(
            model_name="address",
            name="bankaccount",
            field=models.ForeignKey(
                blank=True,
                help_text="Z.B. für Rückzahlung Nebenkosten",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.BankAccount",
                verbose_name="Kontoverbindung",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="bankaccount",
            field=models.ForeignKey(
                blank=True,
                help_text="Bankverbindung der Person/Organisation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.BankAccount",
                verbose_name="Kontoverbindung",
            ),
        ),
    ]
