# Generated by Django 4.2.24 on 2025-09-29 14:56

# python
# File: 'django/geno/migrations/0010_bankaccount_alter_address_bankaccount_and_more.py'
import django.db.models.deletion
from django.db import migrations, models
from stdnum import iban as iban_util


def parse_iban_field(value: str | None):
    if not value:
        return "empty", None, None
    parts = [p.strip() for p in value.split(",", 1)]
    iban_part = parts[0]
    bank_name = parts[1] if len(parts) > 1 else None
    if iban_util.is_valid(iban_part):
        return (
            ("valid_iban_with_bank", iban_part, bank_name)
            if bank_name
            else ("valid_iban", iban_part, None)
        )
    return "other", value, None


def populate_bankaccount_fk(apps, schema_editor):
    Address = apps.get_model("geno", "Address")
    Contract = apps.get_model("geno", "Contract")
    BankAccount = apps.get_model("geno", "BankAccount")

    for add in Address.objects.all().only("id", "bankaccount"):
        raw = (add.bankaccount or "").strip()
        if raw == "":
            add.bankaccount_new_id = None
        else:
            kind, val, bank_name = parse_iban_field(raw)
            if kind == "valid_iban_with_bank":
                bank, _ = BankAccount.objects.get_or_create(
                    iban=val, financial_institution=bank_name
                )
            elif kind == "valid_iban":
                bank, _ = BankAccount.objects.get_or_create(iban=val)
            else:
                bank, _ = BankAccount.objects.get_or_create(comment=raw)
            add.bankaccount_new_id = bank.id
        add.save(update_fields=["bankaccount_new"])

    for cont in Contract.objects.all().only("id", "bankaccount"):
        raw = (cont.bankaccount or "").strip()
        if raw == "":
            cont.bankaccount_new_id = None
        else:
            kind, val, bank_name = parse_iban_field(raw)
            if kind == "valid_iban_with_bank":
                bank, _ = BankAccount.objects.get_or_create(
                    iban=val, financial_institution=bank_name
                )
            elif kind == "valid_iban":
                bank, _ = BankAccount.objects.get_or_create(iban=val)
            else:
                bank, _ = BankAccount.objects.get_or_create(comment=raw)
            cont.bankaccount_new_id = bank.id
        cont.save(update_fields=["bankaccount_new"])


def reverse_populate_bankaccount_fk(apps, schema_editor):
    Address = apps.get_model("geno", "Address")
    Contract = apps.get_model("geno", "Contract")
    BankAccount = apps.get_model("geno", "BankAccount")

    for add in Address.objects.all().only("id", "bankaccount_new"):
        if add.bankaccount_new_id is None:
            add.bankaccount = ""
        else:
            bank = BankAccount.objects.get(id=add.bankaccount_new_id)
            if bank.iban:
                val = bank.iban
                if bank.financial_institution:
                    val = f"{val}, {bank.financial_institution}"
            else:
                val = bank.comment or ""
            add.bankaccount = val
        add.save(update_fields=["bankaccount"])

    for cont in Contract.objects.all().only("id", "bankaccount_new"):
        if cont.bankaccount_new_id is None:
            cont.bankaccount = ""
        else:
            bank = BankAccount.objects.get(id=cont.bankaccount_new_id)
            if bank.iban:
                val = bank.iban
                if bank.financial_institution:
                    val = f"{val}, {bank.financial_institution}"
            else:
                val = bank.comment or ""
            cont.bankaccount = val
        cont.save(update_fields=["bankaccount"])


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0009_nk_flat"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(max_length=500, blank=True, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("iban", models.CharField(max_length=34, blank=True, verbose_name="IBAN")),
                (
                    "financial_institution",
                    models.CharField(max_length=100, blank=True, verbose_name="Finanzinstitut"),
                ),
                (
                    "account_holders",
                    models.CharField(max_length=100, blank=True, verbose_name="Kontoinhaber"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="address",
            name="bankaccount_new",
            field=models.ForeignKey(
                to="geno.BankAccount",
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                verbose_name="Kontoverbindung",
                help_text="Z.B. für Rückzahlung Nebenkosten",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="bankaccount_new",
            field=models.ForeignKey(
                to="geno.BankAccount",
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                verbose_name="Kontoverbindung",
                help_text="Bankverbindung der Person/Organisation",
            ),
        ),
        migrations.RunPython(populate_bankaccount_fk, reverse_populate_bankaccount_fk),
        migrations.RemoveField(model_name="address", name="bankaccount"),
        migrations.RemoveField(model_name="contract", name="bankaccount"),
        migrations.RenameField(
            model_name="address", old_name="bankaccount_new", new_name="bankaccount"
        ),
        migrations.RenameField(
            model_name="contract", old_name="bankaccount_new", new_name="bankaccount"
        ),
    ]
