# Generated by Django 4.2.24 on 2025-10-14 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0011_tenantsview_alter_rentalunit_import_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={"verbose_name": "Bankkonto", "verbose_name_plural": "Bankkonten"},
        ),
        migrations.AlterModelOptions(
            name="contract",
            options={
                "ordering": ("date_end", "-date"),
                "permissions": (
                    (
                        "rental_contracts",
                        "Kann Mietverträge erstellen, NK-Abrechung, Pflichtanteile überprüfen",
                    ),
                    (
                        "rental_objects",
                        "Kann Mieter-/Objektespiegel erstellen und Mietobjekt-Dokumente erstellen",
                    ),
                ),
                "verbose_name": "Vertrag",
                "verbose_name_plural": "Verträge",
            },
        ),
        migrations.AlterModelOptions(
            name="share",
            options={
                "permissions": (
                    ("canview_share", "Can view shares"),
                    ("canview_share_overview", "Can see share overview"),
                    ("confirm_share", "Kann Betiligungen bestätigen"),
                    (
                        "share_interest_statements",
                        "Kann Zins-/Kontoauszüge erstellen und Zinsen anpassen",
                    ),
                    ("share_mailing", "Kann Mailing zu Beteiligungen erstellen"),
                ),
                "verbose_name": "Beteiligung",
                "verbose_name_plural": "Beteiligungen",
            },
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["name"],
                "verbose_name": "Externe Nutzer:in",
                "verbose_name_plural": "Externe Nutzer:innen",
            },
        ),
        migrations.AlterModelOptions(
            name="tenantsview",
            options={
                "managed": False,
                "ordering": ["bu_name", "ru_name"],
                "verbose_name": "Mieter:innenspiegel",
                "verbose_name_plural": "Mieter:innenspiegel",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="building",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="child",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="child",
            name="name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_child",
                to="geno.address",
                verbose_name="Person",
            ),
        ),
        migrations.AlterField(
            model_name="contenttemplate",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="contenttemplateoption",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="contenttemplateoption",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.contenttemplateoptiontype",
                verbose_name="Variable",
            ),
        ),
        migrations.AlterField(
            model_name="contenttemplateoptiontype",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="billing_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_billing_contracts",
                to="geno.contract",
                verbose_name="In Inkasso von diesem Vertrag integrieren",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="main_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="address_main_contracts",
                to="geno.address",
                verbose_name="Kontaktperson/Hauptmieter*in",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="main_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_contract",
                to="geno.contract",
                verbose_name="Hauptvertrag",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="document",
            name="doctype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.documenttype",
                verbose_name="Dokumenttyp",
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="OpenDocument Dokumentvorlage",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.contenttemplate",
                verbose_name="Vorlage",
            ),
        ),
        migrations.AlterField(
            model_name="genericattribute",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.contract",
                verbose_name="Vertrag",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.invoicecategory",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.address",
                verbose_name="Person/Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="invoicecategory",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="invoicecategory",
            name="email_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.contenttemplate",
                verbose_name="Email-Vorlage",
            ),
        ),
        migrations.AlterField(
            model_name="lookuptable",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="member",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.address",
                verbose_name="Person/Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="memberattribute",
            name="attribute_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.memberattributetype",
                verbose_name="Attributtyp",
            ),
        ),
        migrations.AlterField(
            model_name="memberattribute",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="memberattribute",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.member",
                verbose_name="Mitglied",
            ),
        ),
        migrations.AlterField(
            model_name="memberattributetype",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.registrationslot",
                verbose_name="Datum/Zeit Beginn",
            ),
        ),
        migrations.AlterField(
            model_name="registrationevent",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="registrationslot",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="registrationslot",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.registrationevent",
                verbose_name="Anlass",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.building",
                verbose_name="Liegenschaft",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="share",
            name="attached_to_building",
            field=models.ForeignKey(
                blank=True,
                help_text="Nur ausfüllbar wenn kein Vertrag gewählt ist.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="building_attached_shares",
                to="geno.building",
                verbose_name="Liegenschaft",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="attached_to_contract",
            field=models.ForeignKey(
                blank=True,
                help_text="Falls leer werden Anteilscheine automatisch als Pflichtanteile zu Verträgen zugewiesen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_attached_shares",
                to="geno.contract",
                verbose_name="Fixe Zuteilung als Pflichtanteil für Vertrag",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="share",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.address",
                verbose_name="Person/Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="share_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.sharetype",
                verbose_name="Beteiligungstyp",
            ),
        ),
        migrations.AlterField(
            model_name="sharetype",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.building",
                verbose_name="Gebäude",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_tenant",
                to="geno.address",
                verbose_name="Person",
            ),
        ),
    ]
