# Generated by Django 4.2.25 on 2025-10-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0013_building_accounting_postfix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="date_since",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Start des Mietverhältnisses (ggf. abweichend vom Vertragsbeginn). Wird in keiner Berechnung verwendet.",
                null=True,
                verbose_name="Verhältnis seit",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="rent_reservation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Mietzinsvorbehalt Nettomiete (Fr./Monat)",
            ),
        ),
        migrations.RemoveField(
            model_name="contract",
            name="children_old",
        ),
    ]
