# Generated by Django 4.2.25 on 2025-10-28 15:52

from django.db import migrations, models


def add_book_type_prefix(apps, schema_editor):
    """Add the previous default book type prefix to transaction refs"""
    invoice_class = apps.get_model("geno", "Invoice")
    for invoice in invoice_class.objects.all():
        if invoice.fin_transaction_ref and not invoice.fin_transaction_ref.startswith("gnc_0_"):
            invoice.fin_transaction_ref = f"gnc_0_{invoice.fin_transaction_ref}"
            invoice.save()


def remove_book_type_prefix(apps, schema_editor):
    """Remove book type prefix from transaction refs"""
    invoice_class = apps.get_model("geno", "Invoice")
    for invoice in invoice_class.objects.all():
        if invoice.fin_transaction_ref.startswith("gnc_0_"):
            invoice.fin_transaction_ref = invoice.fin_transaction_ref[6:]
            invoice.save()


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0014_contract_date_since_rent_reduction_children_old"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="gnucash_id",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="gnc_account",
            new_name="fin_account",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="gnc_account_receivables",
            new_name="fin_account_receivables",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="gnc_transaction",
            new_name="fin_transaction_ref",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fin_account",
            field=models.CharField(blank=True, max_length=50, verbose_name="Konto Buchhaltung"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fin_account_receivables",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Konto Forderungen Buchhaltung"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fin_transaction_ref",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="Transaktions-Referenz Buchhaltung"
            ),
        ),
        migrations.RunPython(add_book_type_prefix, reverse_code=remove_book_type_prefix),
    ]
