# Generated by Django 4.2.27 on 2025-12-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0015_remove_address_gnucash_id_rename_invoice_gnc_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="bankaccount",
            field=models.ForeignKey(
                blank=True,
                help_text="Z.B. für Auszahlung Zinsen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.bankaccount",
                verbose_name="Kontoverbindung",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Vorname"),
        ),
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Bei Organisationen: Kontaktperson",
                max_length=150,
                verbose_name="Nachname",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Bei Privatpersonen: leer lassen",
                max_length=150,
                verbose_name="Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="bankaccount",
            field=models.ForeignKey(
                blank=True,
                help_text="Z.B. für Rückzahlung Nebenkosten",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.bankaccount",
                verbose_name="Kontoverbindung",
            ),
        ),
    ]
