# Generated by Django 4.2.27 on 2025-12-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0016_alter_address_bankaccount_alter_address_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="billing_date_end",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Leer lassen, falls bis Vertragsende.",
                null=True,
                verbose_name="Sollstellung bis",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="billing_date_start",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Leer lassen, falls ab Vertragsbeginn.",
                null=True,
                verbose_name="Sollstellung ab",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date",
            field=models.DateField(verbose_name="Vertragsbeginn"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date_end",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Vertragsende"
            ),
        ),
    ]
