# Generated by Django 4.2.27 on 2026-01-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0017_contract_billing_date_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="bankaccount",
            field=models.ForeignKey(
                blank=True,
                help_text="Z.B. für Auszahlung Zinsen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.bankaccount",
                verbose_name="Kontoverbindung/IBAN",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="bankaccount",
            field=models.ForeignKey(
                blank=True,
                help_text="Z.B. für Rückzahlung Nebenkosten",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.bankaccount",
                verbose_name="Kontoverbindung/IBAN",
            ),
        ),
    ]
