# Generated by Django 4.2.28 on 2026-02-26 15:23

from django.db import migrations, models


# Migrate rental objects of type "Jokerzimmer" to "Zimmer" by setting the label to "Jokerzimmer", but ONLY IF the label is empty. If the label is not empty, leave it as is!
def mark_jokerzimmer_as_zimmer_and_set_label(apps, schema_editor):
    RentalUnit = apps.get_model("geno", "RentalUnit")
    for rental in RentalUnit.objects.filter(rental_type="Jokerzimmer"):
        if not rental.label:
            rental.label = "Jokerzimmer"
        rental.rental_type = "Zimmer"
        rental.save(update_fields=["rental_type", "label"])


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0018_alter_address_bankaccount_alter_contract_bankaccount"),
    ]

    operations = [
        migrations.RunPython(mark_jokerzimmer_as_zimmer_and_set_label),
        migrations.AlterField(
            model_name="rentalunit",
            name="rental_type",
            field=models.CharField(
                choices=[
                    ("Wohnung", "Wohnung"),
                    ("Grosswohnung", "Grosswohnung"),
                    ("Zimmer", "Zimmer"),
                    ("Selbstausbau", "Selbstausbau"),
                    ("Kellerabteil", "Kellerabteil"),
                    ("Gewerbe", "Gewerbefläche"),
                    ("Lager", "Lagerraum"),
                    ("Hobby", "Hobbyraum"),
                    ("Gemeinschaft", "Gemeinschaftsräume/Diverses"),
                    ("Parkplatz", "Parkplatz"),
                ],
                max_length=50,
                verbose_name="Typ",
            ),
        ),
    ]
