# Generated by Django 4.2.28 on 2026-02-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0019_alter_rentalunit_rental_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationevent",
            name="enable_telephone",
            field=models.BooleanField(default=False, verbose_name="Telefonnummer abfragen?"),
        ),
    ]
