# Generated by Django 4.2.30 on 2026-05-18 17:52

from django.db import migrations, models

import cohiva.fields
from geno.models import Member, Share


def update_active_members_and_shares(apps, schema_editor):
    def _update_active(model):
        for obj in model.objects.all():
            if obj.is_active() != obj.active:
                obj.active = obj.is_active()
                obj.save()

    _update_active(Member)
    _update_active(Share)


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0021_address_country_iso_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="ahv_number",
            field=cohiva.fields.AHVNumberField(blank=True, verbose_name="AHV-Nummer"),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="billing_period",
            field=models.IntegerField(
                default=1,
                help_text="1 = Monatliche Zahlung, 3 = Vierteljährliche Zahlung, 12 = Jährliche Zahlung etc.",
                verbose_name="Rechnungsperiode (Monate)",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="Z.B. Anteilschein-Nr.",
                max_length=100,
                verbose_name="Beteiligungskennung",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="identifier_external",
            field=models.CharField(
                blank=True,
                help_text="Z.B. Anteilschein-Nr. in Buchhaltung (falls abweichend)",
                max_length=100,
                verbose_name="Beteiligungskennung (extern)",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="import_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Import-ID",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AddField(
            model_name="member",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="nk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Nebenkosten Akonto (Fr./Periode)",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="nk_electricity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Strompauschale (Fr./Periode)",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="nk_flat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Nebenkosten Pauschal (Fr./Periode)",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="rent_netto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="exkl. NK+Strom",
                max_digits=10,
                null=True,
                verbose_name="Netto-Miete (Fr./Periode)",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="rent_year",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Für öffentliche Publikation (Website etc.). Wird aktuell nicht mehr verwendet.",
                max_digits=11,
                null=True,
                verbose_name="Nettomiete publiziert (Fr./Jahr)",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="note",
            field=models.TextField(blank=True, verbose_name="Zusatzinfo"),
        ),
        migrations.RunPython(update_active_members_and_shares, migrations.RunPython.noop),
    ]
