# Generated by Django 4.2.29 on 2026-04-13 12:36

from django.db import migrations, models

import cohiva.fields


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0021_address_country_iso_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="ahv_number",
            field=cohiva.fields.AHVNumberField(blank=True, verbose_name="AHV-Nummer"),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="payment_period",
            field=models.IntegerField(
                default=1,
                help_text="1 = Monatliche Zahlung, 3 = Vierteljährliche Zahlung, 12 = Jährliche Zahlung etc.",
                verbose_name="Zahlungsperiode (Monate)",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="Z.B. Anteilschein-Nr.",
                max_length=100,
                verbose_name="Beteiligungskennung",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="identifier_external",
            field=models.CharField(
                blank=True,
                help_text="Z.B. Anteilschein-Nr. in Buchhaltung (falls abweichend)",
                max_length=100,
                verbose_name="Beteiligungskennung (extern)",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="import_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Import-ID",
            ),
        ),
    ]
