# Generated by Django 4.2.30 on 2026-05-18 17:52

import datetime

from django.db import migrations, models

import cohiva.fields


def update_active_members_and_shares(apps, schema_editor):
    Member = apps.get_model("geno", "Member")
    Share = apps.get_model("geno", "Share")
    today = datetime.date.today()

    for obj in Member.objects.all():
        is_active = obj.date_leave is None or obj.date_leave >= today
        if is_active != obj.active:
            obj.active = is_active
            obj.save()

    # Historical field name is `date_end`, which is renamed to `repayment_date`
    # in migration 0029.
    for obj in Share.objects.all():
        is_active = obj.date_end is None or obj.date_end >= today
        if is_active != obj.active:
            obj.active = is_active
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0022_invoicecategory_building_based_cost_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="ahv_number",
            field=cohiva.fields.AHVNumberField(blank=True, verbose_name="AHV-Nummer"),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="billing_period",
            field=models.IntegerField(
                default=1,
                help_text="1 = Monatliche Zahlung, 3 = Vierteljährliche Zahlung, 12 = Jährliche Zahlung etc.",
                verbose_name="Rechnungsperiode (Monate)",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="Z.B. Anteilschein-Nr.",
                max_length=100,
                verbose_name="Beteiligungskennung",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="identifier_external",
            field=models.CharField(
                blank=True,
                help_text="Z.B. Anteilschein-Nr. in Buchhaltung (falls abweichend)",
                max_length=100,
                verbose_name="Beteiligungskennung (extern)",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="import_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Import-ID",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AddField(
            model_name="member",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="nk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Nebenkosten Akonto (Fr./Periode)",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="nk_electricity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Strompauschale (Fr./Periode)",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="nk_flat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Nebenkosten Pauschal (Fr./Periode)",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="rent_netto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="exkl. NK+Strom",
                max_digits=10,
                null=True,
                verbose_name="Netto-Miete (Fr./Periode)",
            ),
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="rent_year",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Für öffentliche Publikation (Website etc.). Wird aktuell nicht mehr verwendet.",
                max_digits=11,
                null=True,
                verbose_name="Nettomiete publiziert (Fr./Jahr)",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="note",
            field=models.TextField(blank=True, verbose_name="Zusatzinfo"),
        ),
        migrations.RunPython(update_active_members_and_shares, migrations.RunPython.noop),
    ]
