# Generated by Django 4.2.29 on 2026-06-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0023_address_ahv_number_rentalunit_billing_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.address",
                verbose_name="Person/Organisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_leave__isnull", True),
                    ("date_leave__gte", models.F("date_join")),
                    _connector="OR",
                ),
                name="member_date_leave_gte_date_join",
            ),
        ),
    ]
