# Generated by Django 4.2.30 on 2026-06-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0024_member_name_to_fk_and_date_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="telephone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
        ),
    ]
