# Generated by Django 4.2.30 on 2026-07-02 09:59

import django.db.models.deletion
from django.db import migrations, models


def migrate_template(apps, schema_editor):
    doctype_model = apps.get_model("geno", "DocumentType")

    for obj in doctype_model.objects.all():
        if obj.template:
            obj.templates.add(obj.template)


def migrate_template_reverse(apps, schema_editor):
    doctype_model = apps.get_model("geno", "DocumentType")

    for obj in doctype_model.objects.all():
        template = obj.templates.first()
        if template:
            obj.template = template
            obj.save(update_fields=["template"])


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0026_convert_uuids_from_char"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.contenttemplate",
                verbose_name="Vorlage",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="templates",
            field=models.ManyToManyField(
                blank=True,
                help_text="Verfügbar OpenDocument Dokumentvorlagen",
                limit_choices_to={"template_type": "OpenDocument"},
                related_name="document_types",
                to="geno.contenttemplate",
                verbose_name="Vorlagen",
            ),
        ),
        migrations.RunPython(migrate_template, migrate_template_reverse),
        migrations.RemoveField(
            model_name="documenttype",
            name="template",
        ),
    ]
