# Generated by Django 4.2.30 on 2026-07-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0026_convert_uuids_from_char"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttype",
            name="template",
        ),
        migrations.AddField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.contenttemplate",
                verbose_name="Vorlage",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="templates",
            field=models.ManyToManyField(
                blank=True,
                help_text="Verfügbar OpenDocument Dokumentvorlagen",
                limit_choices_to={"template_type": "OpenDocument"},
                related_name="document_types",
                to="geno.contenttemplate",
                verbose_name="Vorlagen",
            ),
        ),
    ]
