# Generated by Django 4.2.30 on 2026-07-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0027_alter_documenttype_template_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='template_file',
        ),
    ]
