# Generated by Django 5.2.16 on 2026-07-27 12:51

import datetime

from django.db import migrations, models


def update_active_members_and_shares(apps, schema_editor):
    Contract = apps.get_model("geno", "Contract")

    def _is_active(obj):
        today = datetime.date.today()
        return obj.date_end is None or obj.date_end >= today

    for obj in Contract.objects.all():
        active = _is_active(obj)
        if obj.active != active:
            obj.active = active
            obj.save(update_fields=["active"])

class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0028_remove_documenttype_template_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.RunPython(update_active_members_and_shares, migrations.RunPython.noop),
    ]
