# Generated by Django 5.2.16 on 2026-07-15 14:43

import cohiva.fields
import cohiva.utils.countries
import cohiva.utils.settings
import django.db.models.deletion
import geno.model_fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0028_remove_documenttype_template_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAddress',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Kommentar')),
                ('ts_created', models.DateTimeField(blank=True, editable=False, verbose_name='Erstellt')),
                ('ts_modified', models.DateTimeField(blank=True, editable=False, verbose_name='Geändert')),
                ('organization', models.CharField(blank=True, help_text='Bei Privatpersonen: leer lassen', max_length=150, verbose_name='Organisation')),
                ('name', models.CharField(blank=True, help_text='Bei Organisationen: Kontaktperson', max_length=150, verbose_name='Nachname')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Vorname')),
                ('title', models.CharField(blank=True, choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Divers', 'Divers'), ('Paar', 'Familie/Paar'), ('Org', 'Organisation/Firma')], max_length=20, verbose_name='Anrede')),
                ('formal', models.CharField(choices=[('Du', 'Du/Ihr'), ('Sie', 'Sie')], default=cohiva.utils.settings.get_default_formal_choice, max_length=20, verbose_name='Duzen')),
                ('extra', models.CharField(blank=True, help_text='z.B. c/o (optional)', max_length=100, verbose_name='Adresszusatz')),
                ('street_name', models.CharField(blank=True, max_length=100, verbose_name='Strasse')),
                ('house_number', models.CharField(blank=True, max_length=100, verbose_name='Hausnummer')),
                ('po_box', models.BooleanField(default=False, verbose_name='Postfach')),
                ('po_box_number', models.CharField(blank=True, max_length=100, verbose_name='Postfach Nr.')),
                ('city_zipcode', models.CharField(blank=True, max_length=30, verbose_name='PLZ')),
                ('city_name', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('country', models.CharField(blank=True, choices=[('CH', 'Schweiz'), ('DE', 'Deutschland'), ('AT', 'Österreich'), ('FR', 'Frankreich'), ('IT', 'Italien'), ('AF', 'Afghanistan'), ('EG', 'Ägypten'), ('AL', 'Albanien'), ('DZ', 'Algerien'), ('AS', 'Amerikanisch-Samoa'), ('VI', 'Amerikanische Jungferninseln'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarktis'), ('AG', 'Antigua und Barbuda'), ('GQ', 'Äquatorialguinea'), ('AR', 'Argentinien'), ('AM', 'Armenien'), ('AW', 'Aruba'), ('AZ', 'Aserbaidschan'), ('ET', 'Äthiopien'), ('AU', 'Australien'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesch'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgien'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivien, Plurinationaler Staat'), ('BQ', 'Bonaire, Sint Eustatius und Saba'), ('BA', 'Bosnien und Herzegowina'), ('BW', 'Botsuana'), ('BV', 'Bouvet-Insel'), ('BR', 'Brasilien'), ('VG', 'Britische Jungferninseln'), ('IO', 'Britisches Territorium im Indischen Ozean'), ('BN', 'Brunei Darussalam'), ('BG', 'Bulgarien'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KY', 'Cayman-Inseln'), ('CL', 'Chile'), ('CN', 'China'), ('CK', 'Cookinseln'), ('CR', 'Costa Rica'), ('CI', "Côte d'Ivoire"), ('CW', 'Curaçao'), ('DK', 'Dänemark'), ('CD', 'Demokratische Republik Kongo'), ('DM', 'Dominica'), ('DO', 'Dominikanische Republik'), ('DJ', 'Dschibuti'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('ER', 'Eritrea'), ('EE', 'Estland'), ('SZ', 'Eswatini'), ('FK', 'Falklandinseln (Malwinen)'), ('FO', 'Färöer-Inseln'), ('FJ', 'Fidschi'), ('FI', 'Finnland'), ('GF', 'Französisch-Guyana'), ('PF', 'Französisch-Polynesien'), ('TF', 'Französische Süd- und Antarktisgebiete'), ('GA', 'Gabun'), ('GM', 'Gambia'), ('GE', 'Georgien'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GD', 'Grenada'), ('GR', 'Griechenland'), ('GL', 'Grönland'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard und McDonaldinseln'), ('VA', 'Heiliger Stuhl (Staat Vatikanstadt)'), ('HN', 'Honduras'), ('HK', 'Hongkong'), ('IN', 'Indien'), ('ID', 'Indonesien'), ('IM', 'Insel Man'), ('IQ', 'Irak'), ('IR', 'Iran, Islamische Republik'), ('IE', 'Irland'), ('IS', 'Island'), ('IL', 'Israel'), ('JM', 'Jamaika'), ('JP', 'Japan'), ('YE', 'Jemen'), ('JE', 'Jersey'), ('JO', 'Jordanien'), ('KH', 'Kambodscha'), ('CM', 'Kamerun'), ('CA', 'Kanada'), ('CV', 'Kap Verde'), ('KZ', 'Kasachstan'), ('QA', 'Katar'), ('KE', 'Kenia'), ('KG', 'Kirgisistan'), ('KI', 'Kiribati'), ('CC', 'Kokos-(Keeling-)Inseln'), ('CO', 'Kolumbien'), ('KM', 'Komoren'), ('CG', 'Kongo'), ('KP', 'Korea, Demokratische Volksrepublik'), ('KR', 'Korea, Republik'), ('HR', 'Kroatien'), ('CU', 'Kuba'), ('KW', 'Kuwait'), ('LA', 'Laos, Demokratische Volksrepublik'), ('LS', 'Lesotho'), ('LV', 'Lettland'), ('LB', 'Libanon'), ('LR', 'Liberia'), ('LY', 'Libyen'), ('LI', 'Liechtenstein'), ('LT', 'Litauen'), ('LU', 'Luxemburg'), ('AX', 'Åland-Inseln'), ('MO', 'Macao'), ('MG', 'Madagaskar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Malediven'), ('ML', 'Mali'), ('MT', 'Malta'), ('MA', 'Marokko'), ('MH', 'Marshallinseln'), ('MQ', 'Martinique'), ('MR', 'Mauretanien'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexiko'), ('FM', 'Mikronesien, Föderierte Staaten von'), ('MD', 'Moldau, Republik'), ('MC', 'Monaco'), ('MN', 'Mongolei'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MZ', 'Mosambik'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NC', 'Neukaledonien'), ('NZ', 'Neuseeland'), ('NI', 'Nicaragua'), ('NL', 'Niederlande'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('MP', 'Nördliche Marianen'), ('MK', 'Nordmazedonien'), ('NF', 'Norfolkinsel'), ('NO', 'Norwegen'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PS', 'Palästina, Staat'), ('PW', 'Palau'), ('PA', 'Panama'), ('PG', 'Papua-Neuguinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippinen'), ('PN', 'Pitcairn'), ('PL', 'Polen'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('RE', 'Réunion'), ('RW', 'Ruanda'), ('RO', 'Rumänien'), ('RU', 'Russische Föderation'), ('MF', 'Saint Martin (Französischer Teil)'), ('BL', 'Saint-Barthélemy'), ('SX', 'Saint-Martin (Niederländischer Teil)'), ('SB', 'Salomoninseln'), ('ZM', 'Sambia'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'São Tomé und Príncipe'), ('SA', 'Saudi-Arabien'), ('SE', 'Schweden'), ('SN', 'Senegal'), ('RS', 'Serbien'), ('SC', 'Seychellen'), ('SL', 'Sierra Leone'), ('ZW', 'Simbabwe'), ('SG', 'Singapur'), ('SK', 'Slowakei'), ('SI', 'Slowenien'), ('SO', 'Somalia'), ('GS', 'South Georgia und die Südlichen Sandwichinseln'), ('ES', 'Spanien'), ('LK', 'Sri Lanka'), ('SH', 'St. Helena, Ascension und Tristan da Cunha'), ('KN', 'St. Kitts und Nevis'), ('LC', 'St. Lucia'), ('PM', 'St. Pierre und Miquelon'), ('VC', 'St. Vincent und die Grenadinen'), ('ZA', 'Südafrika'), ('SD', 'Sudan'), ('SS', 'Südsudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard und Jan Mayen'), ('SY', 'Syrien, Arabische Republik'), ('TJ', 'Tadschikistan'), ('TW', 'Taiwan, Chinesische Provinz'), ('TZ', 'Tansania, Vereinigte Republik'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad und Tobago'), ('TD', 'Tschad'), ('CZ', 'Tschechien'), ('TN', 'Tunesien'), ('TR', 'Türkei'), ('TM', 'Turkmenistan'), ('TC', 'Turks- und Caicosinseln'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('HU', 'Ungarn'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('UZ', 'Usbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela, Bolivarische Republik'), ('AE', 'Vereinigte Arabische Emirate'), ('US', 'Vereinigte Staaten'), ('GB', 'Vereinigtes Königreich'), ('VN', 'Vietnam'), ('WF', 'Wallis und Futuna'), ('CX', 'Weihnachtsinseln'), ('EH', 'Westsahara'), ('CF', 'Zentralafrikanische Republik'), ('CY', 'Zypern')], default=cohiva.utils.countries.get_default_country_code, max_length=2, verbose_name='Land')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='2. Telefon')),
                ('telephoneOffice', models.CharField(blank=True, max_length=30, verbose_name='Telefon Geschäft')),
                ('telephoneOffice2', models.CharField(blank=True, max_length=30, verbose_name='2. Telefon Geschäft')),
                ('email', geno.model_fields.LowercaseEmailField(blank=True, max_length=254, verbose_name='Email')),
                ('email2', geno.model_fields.LowercaseEmailField(blank=True, max_length=254, verbose_name='2. Email')),
                ('website', models.CharField(blank=True, max_length=300, verbose_name='Webseite')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('hometown', models.CharField(blank=True, max_length=50, verbose_name='Heimatort')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='Beruf/Ausbildung')),
                ('ahv_number', cohiva.fields.AHVNumberField(blank=True, verbose_name='AHV-Nummer')),
                ('interest_action', models.CharField(blank=True, choices=[('Bank', 'Überweisung auf angegebenes Bankkonto'), ('Loan', 'Dem Darlehen anrechnen'), ('Deposit', 'Dem Depositenkassenkonto anrechnen')], help_text='Für Darlehen. Leer = Nachfragen', max_length=100, verbose_name='Standard-Zinsvergütung')),
                ('paymentslip', models.BooleanField(default=False, help_text='Auswählen für Spezialfälle, welche manuell verarbeitet werden, z.B. Versand per Post statt E-Mail.', verbose_name='Kein automatischer Versand')),
                ('ignore_in_lists', models.BooleanField(default=False, help_text='Auswählen für Personen, die nicht auf Listen wie Bewohnendenspiegel oder Sonnerie/Briefkasten etc. erscheinen sollen.', verbose_name='Für Listen ignorieren')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('import_id', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='Import-ID')),
                ('random_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Zufalls-ID')),
                ('login_permission', models.BooleanField(default=False, verbose_name='Login auch ohne Mitgliedschaft/Mietvertrag erlauben')),
                ('carddav_href', models.CharField(blank=True, max_length=255, verbose_name='carddav_href')),
                ('carddav_etag', models.CharField(blank=True, max_length=255, verbose_name='carddav_etag')),
                ('carddav_syncts', models.DateTimeField(blank=True, null=True, verbose_name='carddav_syncts')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bankaccount', models.ForeignKey(blank=True, db_constraint=False, help_text='Z.B. für Auszahlung Zinsen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geno.bankaccount', verbose_name='Kontoverbindung/IBAN')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Adresse',
                'verbose_name_plural': 'historical Adressen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
