# Generated by Django 5.2.16 on 2026-07-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0028_remove_documenttype_template_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
