# Generated by Django 5.2.17 on 2026-09-04 11:40

import django.db.models.deletion
from django.db import migrations, models


def populate_initial(apps, schema_editor):
    MonthlyWeights = apps.get_model("geno", "MonthlyWeights")
    MonthlyWeights.objects.create(
        name="Standard (uniform)", comment="Jeder Monat wird gleich gewichtet"
    )
    MonthlyWeights.objects.create(
        name="Heizgradtage mit Warmwasser-Aufbereitung",
        weight_01=13.6,
        weight_02=12.1,
        weight_03=11.5,
        weight_04=9.3,
        weight_05=5.6,
        weight_06=3.7,
        weight_07=3.7,
        weight_08=3.6,
        weight_09=3.7,
        weight_10=9.5,
        weight_11=10.7,
        weight_12=13.0,
    )
    MonthlyWeights.objects.create(
        name="Heizgradtage ohne Warmwasser-Aufbereitung",
        weight_01=17.5,
        weight_02=14.5,
        weight_03=13.5,
        weight_04=9.5,
        weight_05=3.5,
        weight_06=0,
        weight_07=0,
        weight_08=0,
        weight_09=1.0,
        weight_10=10.0,
        weight_11=13.5,
        weight_12=17.0,
    )

    RentalUnitSectionWeights = apps.get_model("geno", "RentalUnitSectionWeights")
    RentalUnitSectionWeights.objects.create(
        name="Standard (uniform)", comment="Jeder Bereich wird gleich gewichtet"
    )
    RentalUnitSectionWeights.objects.create(
        name="Nur Wohnen",
        weight_allgemein=0.0,
        weight_wohnen=1.0,
        weight_gewerbe=0.0,
        weight_lager=0.0,
    )
    RentalUnitSectionWeights.objects.create(
        name="Nur Gewerbe",
        weight_allgemein=0.0,
        weight_wohnen=0.0,
        weight_gewerbe=1.0,
        weight_lager=0.0,
    )
    RentalUnitSectionWeights.objects.create(
        name="Nur Lager/Sonstiges",
        weight_allgemein=0.0,
        weight_wohnen=0.0,
        weight_gewerbe=0.0,
        weight_lager=1.0,
    )
    RentalUnitSectionWeights.objects.create(
        name="Ohne Allgemein",
        weight_allgemein=0.0,
        weight_wohnen=1.0,
        weight_gewerbe=1.0,
        weight_lager=1.0,
        comment="Allgemeine Kosten werden gleichmässig auf die anderen Bereiche verteilt",
    )

    VirtualContract = apps.get_model("geno", "VirtualContract")
    VirtualContract.objects.create(
        name="Leerstand",
        description="Für Kosten aus Mietobjekten, die keinen aktiven Vertrag haben.",
        nk_account="4582",
        comment="Kann nicht gelöscht oder umbenannt werden.",
    )
    VirtualContract.objects.create(
        name="Allgemein",
        description="Für Mietobjekte, deren Kosten auf alle anderen Mietobjekte verteilt werden sollen.",
        nk_account="4581",
        comment="Kann nicht gelöscht oder umbenannt werden.",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0031_tenantsview_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyWeights",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Bezeichnung")),
                (
                    "weight_01",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Januar",
                    ),
                ),
                (
                    "weight_02",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Februar",
                    ),
                ),
                (
                    "weight_03",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für März",
                    ),
                ),
                (
                    "weight_04",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für April",
                    ),
                ),
                (
                    "weight_05",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Mai",
                    ),
                ),
                (
                    "weight_06",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Juni",
                    ),
                ),
                (
                    "weight_07",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Juli",
                    ),
                ),
                (
                    "weight_08",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für August",
                    ),
                ),
                (
                    "weight_09",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für September",
                    ),
                ),
                (
                    "weight_10",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Oktober",
                    ),
                ),
                (
                    "weight_11",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für November",
                    ),
                ),
                (
                    "weight_12",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Dezember",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Gewichtungsfaktor pro Monat",
                "verbose_name_plural": "Gewichtungsfaktoren pro Monat",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RentalUnitSectionWeights",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Bezeichnung")),
                (
                    "weight_allgemein",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Bereich «Allgemein»",
                    ),
                ),
                (
                    "weight_wohnen",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Bereich «Wohnen»",
                    ),
                ),
                (
                    "weight_gewerbe",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Bereich «Gewerbe»",
                    ),
                ),
                (
                    "weight_lager",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Gewichtung für Bereich «Lager/Sonstiges»",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Bereichs-Gewichtung für Mietobjekte",
                "verbose_name_plural": "Bereichts-Gewichtungen für Mietobjekte",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VirtualContract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Beschreibung"),
                ),
                (
                    "nk_account",
                    models.CharField(
                        default="6700",
                        max_length=50,
                        verbose_name="Kontonummer in Buchhaltung für Nebenkosten",
                    ),
                ),
                (
                    "nk_account_building_based",
                    models.BooleanField(
                        default=False,
                        help_text="Liegenschafts-Postfix (bspw. 81) wird genutzt um Kontonummer zu bilden. Es resultiert bspw. 300081",
                        verbose_name="Konto liegenschaftsabhängig",
                    ),
                ),
                (
                    "building_based_cost_center",
                    models.BooleanField(
                        default=False,
                        help_text="Fügt Buchungen eine Kostenstelle hinzu, basierend auf dem Liegenschafts-Postfix.",
                        verbose_name="Kostenstelle hinzufügen",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Virtueller Vertrag",
                "verbose_name_plural": "Virtuelle Verträge",
            },
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="section",
            field=models.CharField(
                choices=[
                    ("auto", "Automatisch (aufgrund Typ)"),
                    ("wohnen", "Wohnen"),
                    ("gewerbe", "Gewerbe"),
                    ("lager", "Lager/Sonstiges"),
                ],
                default="auto",
                help_text="Für Ausnahmen kann hier statt «Automatisch» ein Bereich ausgewählt werden.",
                max_length=50,
                verbose_name="Bereichszuordnung",
            ),
        ),
        migrations.CreateModel(
            name="RentalUnitWeightType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=50, verbose_name="Bezeichnung")),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geno.building",
                        verbose_name="Gebäude",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gewichtungsfaktor für Mietobjekte",
                "verbose_name_plural": "Gewichtungsfaktoren für Mietobjekte",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RentalUnitWeight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3, default=1.0, max_digits=10, verbose_name="Wert"
                    ),
                ),
                (
                    "rental_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geno.rentalunit",
                        verbose_name="Mietobjekt",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geno.rentalunitweighttype",
                        verbose_name="Gewichtungsfaktor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gewichtung für Mietobjekte",
                "verbose_name_plural": "Gewichtungen für Mietobjekte",
                "ordering": ["rental_unit", "name"],
            },
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="virtual_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.virtualcontract",
                verbose_name="Virtueller Vertrag",
                help_text=(
                    "Für Zuweisung von Kosten, wenn kein aktiver Vertrag besteht. Wenn nichts "
                    "ausgewählt, wird «Leerstand» verwendet."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalunitweighttype",
            constraint=models.UniqueConstraint(
                fields=("name", "building"), name="unique_rentalunitweighttype_name_per_building"
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalunitweight",
            constraint=models.UniqueConstraint(
                fields=("name", "rental_unit"), name="unique_rentalunitweight_per_type_and_unit"
            ),
        ),
        migrations.RunPython(populate_initial, migrations.RunPython.noop),
    ]
