# Generated by Django 5.2.17 on 2026-10-09 16:51


from django.db import migrations, models

from geno.models import ShareTypeCategory


def guess_new_properties(apps, schema_editor):
    ShareType = apps.get_model("geno", "ShareType")

    for share_type in ShareType.objects.all():
        # Guess properties based on existing name
        if "anteilschein" in share_type.name.lower():
            if "gründung" in share_type.name.lower() or "jurist" in share_type.name.lower():
                share_type.membership_type = "not_flag_02"
            elif "einzel" in share_type.name.lower():
                share_type.membership_type = "flag_02"
            elif (
                "freiwillig" in share_type.name.lower()
                or "wohnungsanteil" in share_type.name.lower()
            ):
                share_type.membership_type = ""
            else:
                share_type.membership_type = "all"
                if "Genossenschaftsanteil" in share_type.name:
                    share_type.is_excluded_from_rental_units = True
        elif "darlehen" in share_type.name.lower():
            share_type.requires_due_date = True
            if "spezial" in share_type.name.lower():
                share_type.category = ShareTypeCategory.SPECIAL_LOAN
                share_type.is_excluded_from_reports = True
            else:
                share_type.category = ShareTypeCategory.LOAN
            if "zinslos" in share_type.name.lower():
                share_type.is_interest_bearing = False
            else:
                share_type.is_interest_bearing = True
        elif "deposit" in share_type.name.lower():
            share_type.category = ShareTypeCategory.DEPOSIT
            share_type.is_interest_bearing = True
        elif "hypothek" in share_type.name.lower():
            share_type.category = ShareTypeCategory.MORTGAGE
        elif "entwicklungsbeitrag" in share_type.name.lower():
            share_type.category = ShareTypeCategory.NON_REPAYABLE
        share_type.save()


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0032_tenantsview_active_fix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sharetype",
            options={
                "ordering": ["active", "display_order", "name"],
                "verbose_name": "Share type",
                "verbose_name_plural": "Share types",
            },
        ),
        migrations.AddField(
            model_name="sharetype",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AddField(
            model_name="sharetype",
            name="category",
            field=models.CharField(
                choices=[
                    ("share", "Share"),
                    ("loan", "Loan"),
                    ("deposit", "Deposit"),
                    ("mortgage", "Mortgage"),
                    ("non_repayable", "Non-repayable Grant"),
                    ("special_loan", "Special Loan"),
                ],
                default="share",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="sharetype",
            name="display_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display order"),
        ),
        migrations.AddField(
            model_name="sharetype",
            name="is_excluded_from_mailings",
            field=models.BooleanField(default=False, verbose_name="Exclude from mailings"),
        ),
        migrations.AddField(
            model_name="sharetype",
            name="is_excluded_from_rental_units",
            field=models.BooleanField(
                default=False,
                help_text="E.g. for shares that should not be counted towards the required sum for a rental unit.",
                verbose_name="Should not be attributed to a rental unit",
            ),
        ),
        migrations.AddField(
            model_name="sharetype",
            name="is_excluded_from_reports",
            field=models.BooleanField(
                default=False, verbose_name="Exclude from reports/statistics"
            ),
        ),
        migrations.AddField(
            model_name="sharetype",
            name="is_interest_bearing",
            field=models.BooleanField(default=False, verbose_name="Interest-bearing"),
        ),
        migrations.AddField(
            model_name="sharetype",
            name="membership_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Voluntary / No mandatory share"),
                    ("all", "All members"),
                    ("flag_01", "Members with flag_01"),
                    ("flag_02", "Members with flag_02"),
                    ("flag_03", "Members with flag_03"),
                    ("flag_04", "Members with flag_04"),
                    ("flag_05", "Members with flag_05"),
                    ("not_flag_01", "Members without flag_01"),
                    ("not_flag_02", "Members without flag_02"),
                    ("not_flag_03", "Members without flag_03"),
                    ("not_flag_04", "Members without flag_04"),
                    ("not_flag_05", "Members without flag_05"),
                ],
                default="",
                max_length=20,
                verbose_name="Membership type",
            ),
        ),
        migrations.AddField(
            model_name="sharetype",
            name="requires_due_date",
            field=models.BooleanField(default=False, verbose_name="Due date required"),
        ),
        migrations.AlterField(
            model_name="sharetype",
            name="description",
            field=models.CharField(max_length=200, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="sharetype",
            name="standard_interest",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Interest rate applies to all shares with interest mode «Standard».",
                max_digits=4,
                verbose_name="Standard interest rate",
            ),
        ),
        migrations.RunPython(guess_new_properties, migrations.RunPython.noop),
    ]
