# Generated by Django 5.2.17 on 2026-10-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0032_tenantsview_active_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Contacts who will receive notifications for this building. When left emtpy, the default email will be used.",
                to="geno.address",
                verbose_name="Contacts",
            ),
        ),
    ]
