# Generated by Django 5.2.17 on 2026-09-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0032_tenantsview_active_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Gespeicherte Dokumentdatei (.pdf oder .odt)', null=True, upload_to='documents/%Y/%m', verbose_name='Datei'),
        ),
    ]
