# Generated by Django 4.2.24 on 2025-10-14 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geno", "0012_alter_bankaccount_options_alter_contract_options_and_more"),
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.reportcategory",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="report",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.address",
                verbose_name="Kontaktperson",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="rental_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.rentalunit",
                verbose_name="Mietobjekt",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.reporttype",
                verbose_name="Meldungstyp",
            ),
        ),
        migrations.AlterField(
            model_name="reportcategory",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reportcategory",
            name="report_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.reporttype",
                verbose_name="Meldungstyp",
            ),
        ),
        migrations.AlterField(
            model_name="reportlogentry",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reportlogentry",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.report",
                verbose_name="Meldung",
            ),
        ),
        migrations.AlterField(
            model_name="reportlogentry",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor:in",
            ),
        ),
        migrations.AlterField(
            model_name="reportpicture",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reportpicture",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.report",
                verbose_name="Meldung",
            ),
        ),
        migrations.AlterField(
            model_name="reporttype",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geno.address",
                verbose_name="Kontaktperson",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.reservationobject",
                verbose_name="Objekt",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="usage_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reservation.reservationusagetype",
                verbose_name="Nutzungsart",
            ),
        ),
        migrations.AlterField(
            model_name="reservationobject",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reservationobject",
            name="reservation_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.reservationtype",
                verbose_name="Reservationstyp",
            ),
        ),
        migrations.AlterField(
            model_name="reservationprice",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reservationprice",
            name="usage_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.reservationusagetype",
                verbose_name="Reservations Nutzungsart",
            ),
        ),
        migrations.AlterField(
            model_name="reservationtype",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="reservationtype",
            name="confirmation_email_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Leer lassen falls keine Bestätigung gesendet werden soll.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.contenttemplate",
                verbose_name="Vorlage Bestätigungs-Email",
            ),
        ),
        migrations.AlterField(
            model_name="reservationusagetype",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
    ]
