# Generated by Django 4.2.30 on 2026-07-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0002_alter_report_category_alter_report_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationtype",
            name="show_contacts_in_calendar",
            field=models.BooleanField(
                default=True, verbose_name="Show name of the person in the calendar"
            ),
        ),
        migrations.AddField(
            model_name="reservationtype",
            name="show_rental_units_in_calendar",
            field=models.BooleanField(
                default=False, verbose_name="Show rental units of the person in the calendar"
            ),
        ),
    ]
