# Generated by Django 4.2.26 on 2025-11-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name des Import-Jobs"
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("member_address_it_wgn", "Mitglieder und Adressen (IT-WGN)"),
                            ("tenant_property_it_wgn", "Mieter und Liegenschaften (IT-WGN)"),
                        ],
                        default="member_address",
                        max_length=20,
                        verbose_name="Import-Typ",
                    ),
                ),
                ("file", models.FileField(upload_to="imports/%Y/%m/", verbose_name="Excel-Datei")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("processing", "In Bearbeitung"),
                            ("completed", "Abgeschlossen"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "records_imported",
                    models.IntegerField(default=0, verbose_name="Importierte Datensätze"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Fehlermeldung")),
                (
                    "result_data",
                    models.JSONField(blank=True, null=True, verbose_name="Ergebnisdaten"),
                ),
            ],
            options={
                "verbose_name": "Import-Auftrag",
                "verbose_name_plural": "Import-Aufträge",
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Name")),
                ("row_number", models.IntegerField(verbose_name="Zeilennummer")),
                ("data", models.JSONField(verbose_name="Daten")),
                ("error_message", models.TextField(blank=True, verbose_name="Fehlermeldung")),
                ("success", models.BooleanField(default=False, verbose_name="Erfolgreich")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="importer.importjob",
                        verbose_name="Import-Auftrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import-Datensatz",
                "verbose_name_plural": "Import-Datensätze",
                "ordering": ["job", "row_number"],
            },
        ),
    ]
