# Generated by Django 4.2.26 on 2025-11-13 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("member_address", "Mitglieder und Adressen"),
                            ("tenant_property", "Mieter und Liegenschaften"),
                        ],
                        default="member_address",
                        max_length=20,
                        verbose_name="Import-Typ",
                    ),
                ),
                ("file", models.FileField(upload_to="imports/%Y/%m/", verbose_name="Excel-Datei")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("processing", "In Bearbeitung"),
                            ("completed", "Abgeschlossen"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "records_imported",
                    models.IntegerField(default=0, verbose_name="Importierte Datensätze"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Fehlermeldung")),
                (
                    "result_data",
                    models.JSONField(blank=True, null=True, verbose_name="Ergebnisdaten"),
                ),
            ],
            options={
                "verbose_name": "Import-Auftrag",
                "verbose_name_plural": "Import-Aufträge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("row_number", models.IntegerField(verbose_name="Zeilennummer")),
                ("data", models.JSONField(verbose_name="Daten")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Fehlermeldung")),
                ("success", models.BooleanField(default=False, verbose_name="Erfolgreich")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="importer.importjob",
                        verbose_name="Import-Auftrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import-Datensatz",
                "verbose_name_plural": "Import-Datensätze",
                "ordering": ["job", "row_number"],
            },
        ),
    ]
