# Generated by Django 4.2.28 on 2026-02-17 14:18

import django.core.files.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0002_importjob_override_existing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="file",
            field=models.FileField(
                upload_to="imports/%Y/%m/",
                verbose_name="Excel-Datei",
                storage=django.core.files.storage.FileSystemStorage(location=settings.SMEDIA_ROOT),
            ),
        )
    ]
