# Generated by Django 4.2.29 on 2026-04-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0003_alter_importjob_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("member_address_it_wgn", "Mitglieder und Adressen (IT-WGN)"),
                    ("tenant_property_it_wgn", "Mieter und Liegenschaften (IT-WGN)"),
                    ("member_address_shares_vfn", "Mitglieder, Adressen und Anteile (VFN)"),
                    ("tenant_property_vfn", "Liegenschaften und Mietobjekte (VFN)"),
                ],
                default="member_address",
                max_length=40,
                verbose_name="Import-Typ",
            ),
        ),
    ]
