name: 🐛 Bug oder Fehler
description: Bug oder Fehler melden
labels: []
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Danke, dass du dir die Zeit nimmst, diesen Fehler zu melden und die folgenden Informationen zusammen zu tragen!
  - type: input
    id: component
    attributes:
      label: Betroffene Komponente(n)
      description: Welche Komponente(n) von COHVIA sind betroffen?
      placeholder: "COHIVA ERP, Seafile (Deteiablage), App, Rocket Chat, ..."
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Betroffene Version
      description: Welche Version von COHVIA verwenden Sie?
      placeholder: "v1.4.3"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Nachvollziehbarkeit / Reproduzierbarkeit
      description: Beschreibe die Schritte, um das Problem zu reproduzieren.
      placeholder: "1. Gehe zu '...'\n2. Klicke auf '....'\n3. Scrolle nach unten zu '....'\n4. Sieh den Fehler"
    validations:
      required: false
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Erwartetes Verhalten
      description: Wie sollte sich das System eigentlich verhalten?
      placeholder: "Beschreibe hier, wie sich das System deiner Meinung nach verhalten sollte, damit es für dich richtig funktioniert."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Falls du Screenshots hast, bitte hier einfügen. Diese helfen uns sehr!
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Umgebung
      description: Falls du Informationen über deine Umgebung hast, z.B. Betriebssystem, Browser, App-Version, etc., kannst du diese hier angeben. Diese Informationen können uns helfen, das Problem besser zu verstehen und zu beheben.
    validations:
      required: false
