# Generated by Django 4.2.24 on 2025-10-14 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0012_alter_bankaccount_options_alter_contract_options_and_more"),
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenantadmin",
            options={
                "ordering": ["name"],
                "verbose_name": "Admin externer Nutzer:innen",
                "verbose_name_plural": "Admins externer Nutzer:innen",
            },
        ),
        migrations.AlterField(
            model_name="tenantadmin",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="tenantadmin",
            name="name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_tenantadmin",
                to="geno.address",
                verbose_name="Person",
            ),
        ),
    ]
