# Generated by Django 4.2.30 on 2026-07-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("portal", "0002_alter_tenantadmin_options_alter_tenantadmin_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthAppSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notify_on_first_login",
                    models.BooleanField(
                        default=False,
                        help_text="Send a notification email if a user logs in to this app for the first time.",
                        verbose_name="Notify admin about new users",
                    ),
                ),
                (
                    "notify_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address to send notifications to. If empty, the default admin email will be used.",
                        max_length=254,
                        null=True,
                        verbose_name="Notification email address",
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth application settings",
                "verbose_name_plural": "OAuth application settings",
            },
        ),
        migrations.CreateModel(
            name="OAuthUserStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_login_at", models.DateTimeField(verbose_name="First login at")),
                ("last_seen_at", models.DateTimeField(verbose_name="Last token issued at")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth user stats",
                "verbose_name_plural": "OAuth user stats",
                "unique_together": {("user", "application")},
            },
        ),
        migrations.CreateModel(
            name="OAuthAppPermissionRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user", "Alle aktiven Benutzer:innen"),
                            ("member", "Alle Mitglieder"),
                            ("renter", "Alle Mieter:innen"),
                            ("community", "Alle in der Siedlung"),
                        ],
                        help_text="Apply rule to users with this role. If left empty if matches ALL users.",
                        max_length=30,
                        verbose_name="User role",
                    ),
                ),
                (
                    "role_or_group_must_match",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled only one of the settings above must match. If disabled, both must match.",
                        verbose_name="User role OR group must match",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order of the rule. Rules are applied in order, first match wins.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("allow", "Allow access"), ("deny", "Deny access")],
                        help_text="Action to take when the rule matches.",
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "application_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="portal.oauthappsettings",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Apply rule to users in this Group. If left empty it matches ALL users.",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth access permission rule",
                "verbose_name_plural": "OAuth access permission rules",
                "ordering": ["application_settings", "order"],
                "unique_together": {("application_settings", "order")},
            },
        ),
    ]
