#!/bin/bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo -e "${BLUE}======================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}======================================${NC}"
    echo
}

print_step() {
    echo -e "${GREEN}➜${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

# Parse arguments
FORCE=false
KEEP_VENV=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--force)
            FORCE=true
            shift
            ;;
        --keep-venv)
            KEEP_VENV=true
            shift
            ;;
        -h|--help)
            echo "Usage: ./clean.sh [OPTIONS]"
            echo ""
            echo "Clean up files generated by bootstrap.sh"
            echo ""
            echo "Options:"
            echo "  -f, --force       Skip confirmation prompt"
            echo "  --keep-venv       Keep the virtual environment"
            echo "  -h, --help        Show this help message"
            echo ""
            echo "This will remove:"
            echo "  - Generated config files (base_config.py, settings.py, etc.)"
            echo "  - SAML2 and OAuth2 keys"
            echo "  - Development data directories (django-test/, django-production/)"
            echo "  - Auto-activation files (.venv-path, .envrc)"
            echo "  - Environment file (.env)"
            echo "  - Docker containers and volumes (MariaDB data, Redis data)"
            echo "  - Virtual environment (unless --keep-venv is used)"
            echo ""
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use -h or --help for usage information"
            exit 1
            ;;
    esac
done

print_header "Cohiva Bootstrap Cleanup"

# Show what will be removed
echo "This will remove the following files and directories:"
echo ""
echo "Configuration files:"
echo "  - cohiva/base_config.py"
echo "  - cohiva/settings.py"
echo "  - cohiva/settings_production.py"
echo "  - .env"
echo ""
echo "Keys and certificates:"
echo "  - cohiva/saml2/private.key"
echo "  - cohiva/saml2/public.pem"
echo "  - cohiva/oauth2/oidc.key"
echo ""
echo "Data directories:"
echo "  - django-test/"
echo "  - django-production/"
echo ""
echo "Auto-activation files:"
echo "  - .venv-path"
echo "  - .envrc"
echo ""

if [ "$KEEP_VENV" = false ]; then
    echo "Virtual environment:"
    VENV_PATH=$(cat .venv-path 2>/dev/null || echo "~/.venv/cohiva-dev")
    echo "  - $VENV_PATH"
    echo ""
fi

echo "Symlinked templates (will be removed):"
echo "  - portal/templates/portal/base.html"
echo "  - portal/templates/portal/base_secondary.html"
echo "  - portal/templates/portal/secondary.html"
echo "  - portal/templates/portal/portal_page.html"
echo "  - portal/static"
echo "  - geno/templates/geno/contract_email.html"
echo "  - geno/templates/geno/email_invoice.html"
echo "  - geno/templates/geno/email_rent_bill_first.html"
echo "  - website"
echo ""

# Confirm unless --force
if [ "$FORCE" = false ]; then
    read -p "Are you sure you want to remove all these files? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Cleanup cancelled"
        exit 0
    fi
fi

print_step "Starting cleanup..."
echo

# Stop Docker services and remove volumes
print_step "Stopping Docker services and removing volumes..."
if [ -f docker-compose.dev.yml ]; then
    docker compose -f docker-compose.dev.yml down -v 2>/dev/null || true
    print_info "Docker services stopped and volumes removed"
else
    print_warn "docker-compose.dev.yml not found, skipping Docker cleanup"
fi

# Remove configuration files
print_step "Removing configuration files..."
rm -f cohiva/base_config.py
rm -f cohiva/settings.py
rm -f cohiva/settings_production.py
rm -f .env
print_info "Configuration files removed"

# Remove keys
print_step "Removing keys and certificates..."
rm -f cohiva/saml2/private.key
rm -f cohiva/saml2/public.pem
rm -f cohiva/oauth2/oidc.key
print_info "Keys removed"

# Remove data directories
print_step "Removing data directories..."
rm -rf django-test
rm -rf django-production
print_info "Data directories removed"

# Remove auto-activation files
print_step "Removing auto-activation files..."
rm -f .venv-path
rm -f .envrc
print_info "Auto-activation files removed"

# Remove symlinked templates
print_step "Removing symlinked templates..."
rm -f portal/templates/portal/base.html
rm -f portal/templates/portal/base_secondary.html
rm -f portal/templates/portal/secondary.html
rm -f portal/templates/portal/portal_page.html
rm -f portal/static
rm -f geno/templates/geno/contract_email.html
rm -f geno/templates/geno/email_invoice.html
rm -f geno/templates/geno/email_rent_bill_first.html
rm -f website
print_info "Symlinked templates removed"

# Remove virtual environment (unless --keep-venv)
if [ "$KEEP_VENV" = false ]; then
    print_step "Removing virtual environment..."
    if [ -f .venv-path ]; then
        VENV_PATH=$(cat .venv-path)
    else
        VENV_PATH="$HOME/.venv/cohiva-dev"
    fi

    if [ -d "$VENV_PATH" ]; then
        rm -rf "$VENV_PATH"
        print_info "Virtual environment removed: $VENV_PATH"
    else
        print_warn "Virtual environment not found: $VENV_PATH"
    fi
else
    print_info "Keeping virtual environment (--keep-venv specified)"
fi

echo
print_header "Cleanup Complete!"
echo "All bootstrap-generated files have been removed."
echo ""

if [ "$KEEP_VENV" = true ]; then
    print_info "Virtual environment was preserved"
    echo ""
fi

echo "To set up the development environment again, run:"
echo "  ./bootstrap.sh"
echo ""
