# Generated by Django 4.2.21 on 2025-08-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("pin", models.CharField(max_length=20, verbose_name="PIN")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="Kontostand"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Konto",
                "verbose_name_plural": "Konten",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccountOwner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("owner_id", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Kontobesitzer:in",
                "verbose_name_plural": "Kontobesitzer:innen",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                (
                    "name",
                    models.CharField(
                        default="Buchung", max_length=100, verbose_name="Buchungstyp"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="ACHTUNG: Einkauf negativ! Gutschrift positiv.",
                        max_digits=10,
                        verbose_name="Betrag",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Datum")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Notiz"),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, verbose_name="Transaktions-ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaktion",
                "verbose_name_plural": "Transaktionen",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserAccountSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("value", models.CharField(max_length=255, verbose_name="Wert")),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Kontoeinstellung pro Benutzer",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[("default", "Standard")],
                        default="default",
                        max_length=50,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "qr_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Name auf QR-Rechnung"
                    ),
                ),
                (
                    "qr_line1",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Adress-Zeile 1 auf QR-Rechnung"
                    ),
                ),
                (
                    "qr_line2",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Adress-Zeile 2 auf QR-Rechnung"
                    ),
                ),
                (
                    "qr_iban",
                    models.CharField(
                        blank=True,
                        help_text="Format: CHnnnnnnnnnnnnnnnnnnn",
                        max_length=21,
                        verbose_name="QR-IBAN Nummer für QR-Rechnung",
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Secret für API-Anbindung"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Verkaufsstelle",
                "verbose_name_plural": "Verkaufsstellen",
            },
        ),
        migrations.CreateModel(
            name="VendorAdmin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500, verbose_name="Comment")),
                ("ts_created", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt")),
                ("ts_modified", models.DateTimeField(auto_now=True, verbose_name="Geändert")),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Administrator:in")],
                        default="admin",
                        max_length=50,
                        verbose_name="Typ",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Verkaufsstellenadmin",
                "verbose_name_plural": "Verkaufsstellenadmins",
            },
        ),
    ]
