# Generated by Django 4.2.21 on 2025-08-22 14:59

import django.db.models.deletion
import select2.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geno", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("credit_accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendoradmin",
            name="name",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="geno.address"
            ),
        ),
        migrations.AddField(
            model_name="vendoradmin",
            name="vendor",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credit_accounting.vendor",
                verbose_name="Verkaufsstelle",
            ),
        ),
        migrations.AddField(
            model_name="useraccountsetting",
            name="account",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credit_accounting.account",
                verbose_name="Konto",
            ),
        ),
        migrations.AddField(
            model_name="useraccountsetting",
            name="user",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer:in",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credit_accounting.account",
                verbose_name="Konto",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=select2.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer:in",
            ),
        ),
        migrations.AddField(
            model_name="accountowner",
            name="name",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_owners",
                to="credit_accounting.account",
                verbose_name="Konto",
            ),
        ),
        migrations.AddField(
            model_name="accountowner",
            name="owner_type",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_as_owner",
                to="contenttypes.contenttype",
                verbose_name="Verknüpft mit",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="vendor",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credit_accounting.vendor",
                verbose_name="Verkaufsstelle",
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccountsetting",
            constraint=models.UniqueConstraint(
                fields=("name", "account", "user"), name="unique_name_account_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(fields=("pin", "vendor"), name="unique_pin_vendor"),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("name", "vendor"), name="unique_name_vendor"
            ),
        ),
    ]
