# Generated by Django 4.2.25 on 2025-10-31 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geno", "0002_contenttemplateoptiontype"),
        ("credit_accounting", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="qr_line1",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="qr_line2",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="qr_name",
        ),
        migrations.AddField(
            model_name="vendor",
            name="qr_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geno.address",
                verbose_name="Adresse für QR-Rechnung",
            ),
        ),
    ]
