# Generated by Django 4.2.24 on 2025-10-14 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geno", "0012_alter_bankaccount_options_alter_contract_options_and_more"),
        ("credit_accounting", "0003_remove_vendor_qr_line1_remove_vendor_qr_line2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="account",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credit_accounting.vendor",
                verbose_name="Verkaufsstelle",
            ),
        ),
        migrations.AlterField(
            model_name="accountowner",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="accountowner",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_owners",
                to="credit_accounting.account",
                verbose_name="Konto",
            ),
        ),
        migrations.AlterField(
            model_name="accountowner",
            name="owner_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_as_owner",
                to="contenttypes.contenttype",
                verbose_name="Verknüpft mit",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credit_accounting.account",
                verbose_name="Konto",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer:in",
            ),
        ),
        migrations.AlterField(
            model_name="useraccountsetting",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credit_accounting.account",
                verbose_name="Konto",
            ),
        ),
        migrations.AlterField(
            model_name="useraccountsetting",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="useraccountsetting",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer:in",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="vendoradmin",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="vendoradmin",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="geno.address"
            ),
        ),
        migrations.AlterField(
            model_name="vendoradmin",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="credit_accounting.vendor",
                verbose_name="Verkaufsstelle",
            ),
        ),
    ]
