#
#    __                          __
#   / /____ ___ ____  ___  ___ _/ /       This file is provided to you by https://github.com/tegonal/cohiva
#  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        Copyright 2024 Tegonal Genossenschaft <info@tegonal.com>
#  \__/\__/\_, /\___/_//_/\_,_/_/         It is licensed under GNU Affero General Public License v3
#         /___/                           Please report bugs and contribute back your improvements
#
#                                         Version: v0.1.0-SNAPSHOT
###################################
name: Quality Assurance
on: [ push, pull_request ]

jobs:
  before_pr:
    name: before-pr.sh
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - name: install shellcheck
        run: ./lib/tegonal-scripts/src/ci/install-shellcheck.sh
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.12.10
          ln -s website_example ./django/website
      - name: before-pr.sh
        run: ./scripts/before-pr.sh
